export type DetailedSection=[string,string[]];
export const articleContent:Record<string,DetailedSection[]>={
"cancer-da-pele-sinais-de-alerta":[
["Como o câncer da pele se desenvolve",["O câncer da pele surge quando células acumulam alterações no DNA e passam a crescer sem o controle habitual do organismo. A radiação ultravioleta é um dos principais fatores envolvidos porque pode causar dano repetido às células da epiderme e aos melanócitos, responsáveis pela produção de pigmento.","Carcinoma basocelular, carcinoma espinocelular e melanoma não são a mesma doença. Eles se originam de células diferentes, apresentam comportamentos distintos e exigem decisões próprias sobre biópsia, margens cirúrgicas, estadiamento e acompanhamento."]],
["Como as lesões podem aparecer",["O carcinoma basocelular pode parecer uma pequena elevação brilhante, uma ferida que cicatriza e volta ou uma placa avermelhada. O carcinoma espinocelular pode formar uma área áspera, endurecida, com crosta, dor ou sangramento. Essas descrições orientam, mas não confirmam o diagnóstico.","O melanoma pode surgir em uma pinta preexistente ou como uma lesão nova. Assimetria, bordas irregulares, cores diferentes e evolução são sinais úteis. Algumas formas, porém, têm pouca pigmentação ou aparecem em unhas, palmas e plantas."]],
["O que pode se parecer com câncer da pele",["Pintas benignas, ceratoses seborreicas, verrugas, dermatites, feridas traumáticas e infecções podem imitar tumores. O contrário também ocorre: lesões malignas iniciais podem parecer discretas e assintomáticas.","A comparação com fotografias na internet não é suficiente porque iluminação, localização e fase de evolução mudam a aparência. O diagnóstico diferencial depende do exame completo da lesão e do contexto clínico."]],
["Como é feita a investigação",["O dermatologista examina a pele e pode usar a dermatoscopia, técnica que amplia estruturas e padrões não percebidos a olho nu. Histórico de exposição solar, queimaduras, câncer anterior, imunossupressão e antecedentes familiares ajudam a estimar risco.","Quando a suspeita permanece, a confirmação costuma exigir biópsia. O tipo de amostra depende da hipótese e da localização. No melanoma, espessura e outras características histológicas influenciam as etapas seguintes."]],
["Quais tratamentos podem ser utilizados",["A cirurgia é o tratamento mais frequente para muitos tumores cutâneos localizados. A técnica pode envolver excisão convencional, controle de margens, reconstrução com retalho ou enxerto, conforme o tipo, tamanho e área afetada.","Medicamentos tópicos, destruição local, radioterapia e tratamentos sistêmicos têm indicações específicas. A escolha considera subtipo do tumor, risco de recorrência, estágio, saúde geral e preferências do paciente."]]],
"biopsia-de-pele-quando-e-indicada":[
["Por que uma amostra pode esclarecer o diagnóstico",["Muitas doenças da pele compartilham sinais como vermelhidão, descamação, coceira ou formação de nódulos. A biópsia permite examinar a arquitetura do tecido e as características das células ao microscópio.","Ela pode investigar tumores, doenças inflamatórias, infecções e alterações de cabelos ou unhas. Nem toda lesão precisa de biópsia: a indicação existe quando o resultado pode confirmar uma hipótese ou modificar a conduta."]],
["Quais técnicas são usadas",["Na biópsia por punch, um instrumento circular coleta um pequeno cilindro de pele. O shaving retira uma porção mais superficial. Na biópsia incisional, apenas parte da lesão é amostrada; na excisional, busca-se retirar a lesão inteira.","A melhor técnica depende da profundidade do processo, da suspeita diagnóstica e da região anatômica. Uma amostra superficial demais pode não conter a informação necessária; uma retirada maior do que o necessário pode produzir cicatriz evitável."]],
["Quando outras condições entram no diagnóstico diferencial",["Uma lesão pigmentada pode corresponder a nevo, ceratose seborreica ou melanoma. Uma placa descamativa pode representar psoríase, dermatite, micose ou doença autoimune. Nódulos podem ser inflamatórios, infecciosos ou tumorais.","Por isso, o patologista interpreta o tecido junto com informações clínicas. Fotografias, localização, tempo de evolução e hipóteses do dermatologista aumentam a precisão da correlação clinicopatológica."]],
["Como se preparar e como é o procedimento",["Antes da biópsia, o médico revisa alergias, tendência a sangramento, medicamentos, dispositivos cardíacos e condições que alterem cicatrização. Anticoagulantes não devem ser suspensos sem orientação do profissional que os prescreveu.","O procedimento geralmente utiliza anestesia local. Dependendo da técnica, pode haver ponto e curativo. Dor leve, pequeno sangramento e sensibilidade podem ocorrer; sinais de infecção ou sangramento persistente precisam ser comunicados."]],
["O que acontece depois do laudo",["O resultado pode confirmar o diagnóstico, indicar necessidade de retirada adicional ou sugerir exames complementares. Um laudo não deve ser interpretado isoladamente, porque alguns padrões microscópicos aparecem em mais de uma doença.","Se a amostra não representar a área mais relevante ou se clínica e patologia não coincidirem, revisão de lâminas ou nova biópsia pode ser considerada. O plano final é definido na consulta de retorno."]]],
"queda-de-cabelo-causas":[
["Como funciona o ciclo do cabelo",["Cada folículo alterna fases de crescimento, transição, repouso e queda. Alterações nesse ciclo podem aumentar a quantidade de fios eliminados ou reduzir progressivamente a espessura produzida por cada folículo.","Queda visível não significa necessariamente perda definitiva. No eflúvio telógeno, muitos fios entram em repouso ao mesmo tempo; nas alopecias cicatriciais, a inflamação pode destruir o folículo e tornar a perda permanente."]],
["Padrões e sintomas que ajudam a diferenciar",["Queda difusa após febre, cirurgia, parto, restrição alimentar ou estresse fisiológico sugere eflúvio telógeno. Rarefação gradual no topo pode indicar alopecia androgenética. Placas lisas e delimitadas podem ocorrer na alopecia areata.","Coceira, dor, ardência, descamação, pústulas ou perda das aberturas foliculares apontam para doenças do couro cabeludo e alopecias inflamatórias. A presença desses sintomas modifica a urgência e a investigação."]],
["Principais diagnósticos diferenciais",["Alopecia androgenética, eflúvio telógeno e alopecia areata são causas comuns, mas anemia, alterações tireoidianas, medicamentos, tração, infecções e doenças autoimunes também podem estar envolvidas.","Mais de uma condição pode coexistir. Uma pessoa com predisposição genética pode apresentar eflúvio após uma doença e perceber piora súbita de um afinamento que já ocorria lentamente."]],
["Como é feita a investigação",["A avaliação inclui duração, distribuição, quantidade percebida, eventos recentes, dieta, ciclo menstrual, medicamentos e histórico familiar. O exame observa fios, couro cabeludo, sobrancelhas, unhas e outras áreas quando necessário.","A tricoscopia amplia fios e folículos e ajuda a identificar miniaturização, inflamação e padrões de quebra. Exames laboratoriais são direcionados pelo histórico. Biópsia é reservada para dúvidas diagnósticas ou suspeita de alopecia cicatricial."]],
["Opções terapêuticas",["O tratamento depende da causa. Eflúvio telógeno pede correção do fator associado e tempo para normalização do ciclo. Alopecia androgenética pode exigir terapias que prolonguem o crescimento e reduzam a miniaturização.","Doenças autoimunes, infecciosas ou cicatriciais precisam de tratamento específico. Procedimentos podem complementar alguns planos, mas não substituem diagnóstico. Suplementos só ajudam quando existe deficiência ou indicação definida."]]],
"alopecia-androgenetica":[
["Por que os fios afinam",["Na alopecia androgenética, folículos geneticamente suscetíveis respondem aos andrógenos com ciclos de crescimento progressivamente mais curtos. A cada ciclo, o fio tende a nascer mais fino e curto, processo chamado miniaturização.","A sensibilidade varia entre regiões do couro cabeludo e entre pessoas. A condição pode começar após a puberdade, mas velocidade, extensão e impacto são diferentes em homens e mulheres."]],
["Como se apresenta em homens e mulheres",["Em homens, são frequentes recessão das entradas, alteração da linha frontal e rarefação na coroa. Em mulheres, costuma haver alargamento da risca e redução difusa da densidade no topo, geralmente com preservação da linha frontal.","O couro cabeludo costuma parecer normal e a evolução é gradual. Queda abrupta, placas, dor, descamação intensa ou cicatriz sugerem associação com outra condição."]],
["Diagnósticos que precisam ser considerados",["Eflúvio telógeno pode causar queda difusa e coexistir com alopecia androgenética. Alopecia areata difusa, tração, doenças tireoidianas, deficiência de ferro e alopecias cicatriciais também entram no diagnóstico diferencial.","Em mulheres com irregularidade menstrual, acne importante ou aumento de pelos, o médico pode investigar sinais de excesso androgênico. A maioria das mulheres com padrão feminino, porém, não apresenta alteração hormonal detectável."]],
["Exame e acompanhamento",["A tricoscopia demonstra variação do diâmetro dos fios, aumento de unidades com um único fio e outros sinais de miniaturização. Fotografias padronizadas ajudam a comparar densidade ao longo dos meses.","Exames laboratoriais não são obrigatórios para todos; são solicitados conforme sintomas e histórico. Biópsia é incomum, mas pode ser útil quando o padrão não é típico ou existe suspeita de inflamação cicatricial."]],
["Tratamentos possíveis",["Minoxidil tópico é uma opção amplamente utilizada. Formulações orais, antiandrógenos ou inibidores da 5-alfa-redutase podem ser considerados pelo dermatologista após avaliar sexo, idade, pressão arterial, planejamento reprodutivo e riscos.","Transplante capilar pode redistribuir folículos de uma área doadora estável, mas não interrompe a progressão nos fios não transplantados. Tratamento clínico e expectativas realistas continuam importantes antes e depois da cirurgia."]]],
"psoriase-guia-para-pacientes":[
["O que acontece na psoríase",["A psoríase é uma doença imunomediada: sinais do sistema imune aceleram a renovação da epiderme e mantêm inflamação persistente. O acúmulo de células contribui para placas espessas e descamativas.","Predisposição genética e fatores ambientais interagem. Infecções, alguns medicamentos, tabagismo, obesidade e estresse podem se associar a crises, mas a doença não é causada por falta de higiene e não é contagiosa."]],
["Formas de apresentação",["A forma em placas é a mais comum, com áreas avermelhadas e descamativas em cotovelos, joelhos, couro cabeludo e tronco. Dobras podem apresentar lesões mais lisas; mãos, pés, face e região genital exigem atenção especial.","As unhas podem desenvolver pequenos furos, descolamento, manchas e espessamento. Dor, inchaço ou rigidez articular podem indicar artrite psoriásica e devem ser investigados precocemente."]],
["O que pode parecer psoríase",["Dermatite seborreica, dermatite de contato, micoses, líquen plano e algumas formas de eczema podem produzir placas descamativas. Em dobras, candidíase e outras inflamações podem se confundir com psoríase inversa.","A distribuição das lesões, alterações ungueais, histórico familiar e evolução ajudam na diferenciação. Quando a apresentação é atípica, exame micológico ou biópsia pode ser necessário."]],
["Como a gravidade é avaliada",["A avaliação considera extensão, intensidade, localização e sintomas, mas também impacto em sono, trabalho, relações e saúde mental. Uma área pequena em mãos ou genitais pode causar grande limitação.","O médico pesquisa dor articular e comorbidades cardiometabólicas. Antes de tratamentos sistêmicos, exames variam conforme o medicamento, histórico de infecções, vacinação e outras condições."]],
["Opções de tratamento",["Casos localizados podem ser tratados com medicamentos tópicos e cuidados para reduzir descamação e inflamação. Fototerapia é uma possibilidade para determinadas extensões e padrões.","Doença moderada a grave pode requerer medicamentos sistêmicos convencionais, pequenas moléculas ou imunobiológicos. A escolha considera manifestações, comorbidades, riscos, preferência e acesso, com monitoramento regular."]]],
"dermatite-atopica":[
["Barreira da pele e sistema imune",["Na dermatite atópica, a barreira cutânea perde água com mais facilidade e permite maior contato com irritantes. Ao mesmo tempo, vias do sistema imune mantêm inflamação e coceira.","Genética, microbioma e ambiente participam de maneira variável. A doença não é contagiosa e não resulta de higiene inadequada. Coçar agrava a barreira e alimenta o ciclo coceira-inflamação."]],
["Como muda conforme a idade",["Bebês frequentemente apresentam lesões na face e superfícies externas dos membros. Em crianças maiores, dobras de cotovelos e joelhos são comuns. Adultos podem ter mãos, face, pescoço ou doença mais disseminada.","Ressecamento, vermelhidão, espessamento por coçar e fissuras são manifestações frequentes. A coceira pode interromper o sono e afetar atenção, humor e desempenho escolar ou profissional."]],
["Diagnósticos diferenciais",["Dermatite de contato, escabiose, psoríase, micose, dermatite seborreica e algumas imunodeficiências podem se parecer com eczema. Distribuição, idade de início, contatos familiares e exposição a produtos orientam a diferenciação.","Testes de alergia não são necessários para todos. O teste de contato é indicado quando há suspeita de alergia a substâncias aplicadas na pele; exames alimentares indiscriminados podem produzir resultados sem relevância clínica."]],
["Como é feita a avaliação",["O diagnóstico é principalmente clínico. O médico avalia extensão, intensidade, frequência de crises, infecções, sono e tratamentos já usados. Fotografias podem ajudar quando a pele está melhor no dia da consulta.","Cultura, exame micológico ou biópsia são reservados para situações específicas. Antes de terapia sistêmica, podem ser necessários exames conforme o medicamento escolhido."]],
["Tratamento e prevenção de crises",["Hidratantes, banho adequado e redução de irritantes formam a base do cuidado. Corticoides tópicos e medicamentos não esteroides controlam a inflamação conforme área, idade e gravidade.","Fototerapia, imunossupressores, imunobiológicos e inibidores de JAK podem ser considerados em doença moderada a grave. O plano inclui reconhecer infecção, controlar coceira e usar tratamento de manutenção quando indicado."]]],
"hidradenite-supurativa":[
["O que acontece no folículo",["A hidradenite supurativa começa com obstrução e inflamação do folículo piloso em regiões de dobra. A ruptura folicular libera conteúdo na pele, intensificando inflamação e favorecendo nódulos, abscessos e túneis.","Genética, hormônios, tabagismo e excesso de peso podem influenciar, mas não explicam todos os casos. A doença não é causada por falta de higiene e não é simplesmente uma infecção recorrente."]],
["Apresentação clínica",["Nódulos profundos e dolorosos reaparecem em axilas, virilhas, região glútea, períneo e sob as mamas. Pode haver drenagem, odor, cicatrizes e canais sob a pele.","A repetição nas mesmas áreas é uma pista importante. Dor e receio de vazamento podem limitar roupas, exercício, trabalho, sexualidade e convívio social."]],
["O que pode confundir o diagnóstico",["Furúnculos, cistos epidérmicos, foliculite, doença pilonidal e doença de Crohn perianal podem apresentar nódulos ou secreção. A localização e a recorrência ajudam a diferenciar.","Cultura pode ser necessária quando há suspeita de infecção secundária, mas bactérias não são a causa central da hidradenite. Ultrassom pode mostrar túneis não visíveis em casos selecionados."]],
["Avaliação de gravidade e comorbidades",["O médico registra número e localização das lesões, túneis, cicatrizes, dor e frequência das crises. Sistemas como Hurley e escores dinâmicos ajudam a acompanhar gravidade.","Também é importante pesquisar tabagismo, síndrome metabólica, doença inflamatória intestinal, artrite, ansiedade e depressão. O cuidado pode exigir equipe multidisciplinar."]],
["Opções terapêuticas",["Tratamentos tópicos e antibióticos sistêmicos podem ajudar em situações selecionadas. Terapias hormonais, retinoides e imunobiológicos são consideradas conforme perfil e gravidade.","Drenagem simples alivia um abscesso, mas não controla túneis crônicos. Deroofing e excisão tratam estruturas persistentes. Controle de dor, curativos e apoio para mudanças possíveis de estilo de vida complementam o plano."]]],
"doencas-das-unhas":[
["Como a unidade ungueal funciona",["A unha é formada por matriz, lâmina, leito, pregas e pele sob a borda livre. Alterações em cada parte produzem sinais diferentes, como sulcos, descolamento, espessamento ou mudança de cor.","O crescimento é lento, sobretudo nos pés. Mesmo após controlar a causa, a aparência só melhora conforme uma nova lâmina cresce, o que pode levar meses."]],
["Apresentações mais frequentes",["Micose pode causar espessamento, resíduos sob a unha, fragilidade e descolamento. Trauma repetido produz alterações semelhantes. Psoríase pode causar pequenos furos, manchas amareladas e descolamento.","Dor e inflamação nas bordas sugerem unha encravada ou paroníquia. Faixas pigmentadas podem ser benignas, medicamentosas ou relacionadas a tumores; o padrão e a evolução importam."]],
["Diagnósticos diferenciais",["Onicomicose deve ser diferenciada de psoríase, líquen plano, trauma e distrofias. Uma unha verde pode refletir colonização bacteriana; manchas brancas podem resultar de trauma e não de falta de cálcio.","Faixas escuras podem ocorrer por características étnicas, nevos, trauma ou medicamentos, mas melanoma ungueal precisa ser considerado em lesões novas, assimétricas ou em mudança."]],
["Investigação",["O exame avalia todas as unhas e a pele ao redor. Dermatoscopia ungueal ajuda na análise de pigmentação e estruturas. Para suspeita de fungo, podem ser usados exame direto, cultura, histologia ou testes moleculares.","Biópsia da matriz ou do leito é reservada para suspeita de tumor, doença inflamatória ou diagnóstico persistente. Como o procedimento pode deixar alteração permanente, a indicação e o local da amostra devem ser planejados."]],
["Tratamentos possíveis",["Micose pode exigir tratamento tópico ou oral conforme número de unhas, extensão e doenças associadas. Unha encravada pode ser tratada com medidas conservadoras ou cirurgia da matriz em casos recorrentes.","Psoríase e líquen plano exigem controle da inflamação. Tumores benignos ou malignos podem precisar de cirurgia. Em qualquer caso, o tempo de crescimento da unha deve fazer parte das expectativas."]]]
};
