import type { Specialty } from "./specialty-template";

const process: [string, string][] = [
  ["Escuta e histórico", "Conversa detalhada sobre os sintomas, o tempo de evolução, os tratamentos já realizados e o impacto na rotina."],
  ["Exame dermatológico", "Avaliação dirigida da pele, dos cabelos ou das unhas, com dermatoscopia quando indicada."],
  ["Investigação", "Exames laboratoriais, cultura, exame micológico ou biópsia apenas quando contribuem para o diagnóstico."],
  ["Plano de cuidado", "Tratamento individualizado, orientações práticas e acompanhamento da resposta ao longo do tempo."],
];

export const specialties: Record<string, Specialty> = {
  "dermatologia-clinica": {
    eyebrow: "Dermatologia clínica",
    title: "Cuidado completo para a saúde da pele.",
    lead: "Avaliação e acompanhamento de doenças da pele, dos cabelos e das unhas em adultos, com diagnóstico cuidadoso e plano individualizado, em Copacabana, no Rio de Janeiro.",
    introTitle: "A pele pode revelar condições locais e sistêmicas.",
    intro: [
      "Coceira que não passa, manchas novas, feridas que demoram a cicatrizar, acne, queda de cabelo e outras alterações persistentes podem ter causas muito diferentes entre si. A dermatologia clínica organiza esses sinais: identifica padrões, diferencia condições parecidas e define quando exames complementares realmente acrescentam informação. A pele também pode refletir doenças internas, e a avaliação dermatológica costuma ser o primeiro passo dessa investigação.",
      "Vale procurar avaliação quando uma alteração persiste por semanas, muda de aspecto, causa dor, coceira ou sangramento, ou quando interfere no sono, no trabalho e na autoestima. Também costuma ser recomendável manter consultas de rotina para exame das pintas, especialmente para pessoas de pele clara, com histórico familiar de câncer da pele ou grande exposição solar acumulada — uma realidade comum no Rio de Janeiro.",
      "Na Clínica QARA, em Copacabana, a consulta começa com escuta detalhada e exame completo da pele, dos cabelos e das unhas, com dermatoscopia quando indicada. A partir daí, o dermatologista explica as hipóteses diagnósticas, solicita exames apenas quando necessários e constrói um plano de tratamento compatível com a rotina do paciente, com retornos programados para acompanhar a resposta.",
    ],
    topics: [
      ["Acne e rosácea", "Condições inflamatórias frequentes que causam lesões, vermelhidão persistente e, com o tempo, marcas e cicatrizes. A avaliação identifica o tipo e a gravidade do quadro para definir um tratamento em etapas, com acompanhamento da resposta."],
      ["Manchas e pigmentação", "Melasma, hiperpigmentação pós-inflamatória e outras alterações de cor têm causas e comportamentos distintos. O exame avalia o padrão, a profundidade e a evolução do pigmento antes de definir a estratégia de tratamento e de proteção solar."],
      ["Infecções da pele", "Micoses, infecções bacterianas e virais podem se parecer com outras doenças da pele. Quando há dúvida, exames como o micológico direto e a cultura ajudam a confirmar o diagnóstico antes de iniciar o tratamento adequado."],
      ["Alergias e coceira", "Dermatites de contato, urticária e outras causas de prurido (coceira) exigem investigação cuidadosa do histórico e dos fatores desencadeantes. O plano combina o alívio dos sintomas com a identificação e o afastamento da causa, quando possível."],
      ["Pintas e lesões", "Nevos (pintas), lesões novas ou que mudaram de cor, tamanho ou formato merecem exame clínico e dermatoscópico. A dermatoscopia amplia a imagem da lesão e ajuda a decidir entre acompanhamento, biópsia ou remoção."],
      ["Doenças crônicas", "Condições recorrentes, como eczemas e outras dermatoses de longa duração, pedem acompanhamento contínuo, e não apenas o tratamento das crises. O seguimento permite ajustar o plano conforme a resposta e prevenir complicações."],
    ],
    process,
    doctor: "Dr. Diego Gálvez",
    credential: "CRM-RJ 52-0112387-4 · RQE 57517",
    doctorText: "Dermatologista com atuação clínica e cirúrgica, o Dr. Diego acompanha pacientes em consultas presenciais na clínica e também por telemedicina.",
    doctorImage: "/images/dr-diego.webp",
    faq: [
      ["Quando devo procurar um dermatologista?", "Quando uma alteração da pele, do cabelo ou das unhas persiste por semanas, causa sintomas, muda rapidamente de aspecto ou interfere na qualidade de vida. Consultas de rotina para exame das pintas também costumam ser recomendadas, conforme o perfil de risco de cada pessoa."],
      ["A consulta inclui dermatoscopia?", "A dermatoscopia — exame com uma lente especial que amplia as estruturas da pele — pode ser utilizada quando ajuda na avaliação de pintas, lesões e outras condições. A indicação é feita pelo próprio médico durante a consulta."],
      ["É possível fazer consulta online?", "Alguns quadros e retornos de acompanhamento podem ser avaliados por telemedicina. Outros exigem exame presencial, como a avaliação de pintas e lesões suspeitas; em caso de dúvida, a equipe orienta qual formato é mais adequado para a sua situação."],
      ["Como me preparo para a consulta dermatológica?", "Se possível, compareça com a pele limpa, sem maquiagem e com as unhas sem esmalte, e leve a lista de medicamentos em uso e exames anteriores. Anotar quando a alteração começou e o que já foi tentado também ajuda a avaliação."],
      ["Quais sinais em uma pinta merecem avaliação mais rápida?", "Pintas que mudam de cor, tamanho ou formato, têm bordas irregulares, coçam, sangram ou se destacam das demais devem ser avaliadas sem demora. Feridas que não cicatrizam em algumas semanas também merecem exame dermatológico."],
    ],
    related: [
      ["Acne: além da adolescência", "/blog/acne-tratamento-por-fases"],
      ["Rosácea ou acne?", "/blog/rosacea-diferenca-da-acne"],
      ["Melasma: por que as manchas voltam", "/blog/melasma-por-que-as-manchas-voltam"],
      ["Câncer da pele: sinais de alerta", "/blog/cancer-da-pele-sinais-de-alerta"],
      ["Mapeamento de pintas", "/blog/mapeamento-de-pintas-dermatoscopia-digital"],
    ],
  },
  "unhas": {
    eyebrow: "Dermatologia das unhas",
    title: "Unhas saudáveis começam com um diagnóstico preciso.",
    lead: "Avaliação especializada de alterações de cor, formato, espessura, dor e inflamação das unhas, com investigação diagnóstica dedicada, em Copacabana, no Rio de Janeiro.",
    introTitle: "Nem toda alteração da unha é micose.",
    intro: [
      "As unhas podem mudar de cor, formato ou espessura por muitos motivos: traumas repetidos, micoses, psoríase, doenças inflamatórias, medicamentos e até condições sistêmicas. Como quadros diferentes produzem alterações parecidas, tratar sem confirmar a causa pode significar meses de tratamento sem resultado. A dermatologia das unhas é a área dedicada a investigar e cuidar da unidade ungueal — a unha e as estruturas que a formam.",
      "Vale procurar avaliação quando uma alteração persiste ou avança, quando há dor, inflamação ou secreção ao redor da unha, quando surge uma faixa escura nova ou quando tratamentos anteriores não funcionaram. Alterações em uma única unha, em especial, merecem atenção, pois podem indicar causas locais que exigem exame dirigido.",
      "Na consulta, o dermatologista examina todas as unhas e a pele ao redor, com dermatoscopia quando indicada, e pode coletar material para exame micológico ou cultura. Em casos selecionados, a biópsia da unidade ungueal esclarece o diagnóstico. Definida a causa, o plano pode incluir tratamento clínico, cuidados locais ou procedimento cirúrgico, conforme avaliação.",
    ],
    topics: [
      ["Micose das unhas", "A onicomicose (micose das unhas) causa espessamento, descolamento e mudança de cor, mas outras doenças produzem sinais parecidos. Por isso, a confirmação por exame micológico, cultura ou análise da lâmina costuma preceder o tratamento, escolhido conforme a extensão do quadro."],
      ["Unha encravada", "Ocorre quando a borda da unha penetra a pele ao redor, causando dor, inflamação e, às vezes, infecção. A avaliação define se o quadro pode ser resolvido com medidas clínicas e correção do corte ou se há indicação de procedimento cirúrgico, sobretudo em casos recorrentes."],
      ["Psoríase ungueal", "A psoríase pode afetar as unhas causando pequenos furos (pitting), descolamento, espessamento e manchas, mesmo quando há pouca lesão na pele. O reconhecimento correto evita tratamentos antifúngicos desnecessários e direciona o cuidado para o controle da inflamação."],
      ["Tumores ungueais", "Nódulos, faixas pigmentadas e lesões persistentes sob a unha ou ao redor dela exigem investigação criteriosa, que vai de tumores benignos a lesões que precisam de biópsia. A dermatoscopia e, quando indicado, o exame histológico orientam a conduta."],
      ["Fragilidade e distrofias", "Unhas quebradiças, descamativas, deformadas ou com crescimento alterado podem refletir hábitos, contato com produtos químicos, envelhecimento ou doenças de base. A avaliação busca a causa e orienta cuidados de proteção e tratamento conforme cada caso."],
      ["Cirurgia da unha", "Biópsias, correção de unha encravada e remoção de lesões da unidade ungueal são procedimentos realizados com técnica e anestesia adequadas à região. A indicação é sempre individualizada, considerando diagnóstico, sintomas e recorrência."],
    ],
    process,
    doctor: "Dr. Miguel Ceccarelli",
    credential: "CRM-RJ 52-0109245-6 · RQE 34414",
    doctorText: "Dermatologista com atuação dedicada às doenças das unhas, o Dr. Miguel conduz a investigação diagnóstica e realiza os procedimentos da unidade ungueal quando indicados.",
    doctorImage: "/images/dr-miguel.webp",
    faq: [
      ["Toda unha amarelada é micose?", "Não. Psoríase, traumas repetidos e outras doenças podem causar alterações muito semelhantes às da micose. Por isso, exames como o micológico direto e a cultura podem ser necessários antes de iniciar qualquer tratamento."],
      ["Unha encravada sempre precisa de cirurgia?", "Não. Muitos casos melhoram com medidas clínicas e correção da forma de cortar a unha. A indicação cirúrgica depende da intensidade da inflamação, da recorrência e da anatomia da unha, avaliadas em consulta."],
      ["Faixa escura na unha precisa ser avaliada?", "Sim, especialmente se for nova, estiver mudando ou vier acompanhada de pigmentação na pele ao redor. Muitas faixas têm causa benigna, mas a avaliação dermatológica com dermatoscopia ajuda a identificar os casos que exigem investigação adicional."],
      ["Preciso tirar o esmalte antes da consulta?", "Sim. O ideal é remover esmaltes e alongamentos de todas as unhas alguns dias antes, pois a cobertura pode esconder alterações importantes. Isso também permite a coleta de material para exames, se houver necessidade."],
      ["Quanto tempo dura o tratamento da micose de unha?", "O tempo varia conforme a unha acometida e a extensão do quadro, e costuma acompanhar o crescimento lento da unha — em geral, vários meses. O acompanhamento periódico permite verificar a resposta e ajustar o plano quando necessário."],
    ],
    related: [
      ["Doenças das unhas", "/blog/doencas-das-unhas"],
      ["Unha encravada: tratamento e cirurgia", "/blog/unha-encravada-tratamento-e-cirurgia"],
      ["Micose de unha", "/blog/micose-de-unha-tratamento"],
      ["Psoríase", "/blog/psoriase-guia-para-pacientes"],
    ],
  },
  "doencas-inflamatorias": {
    eyebrow: "Psoríase e doenças inflamatórias",
    title: "Controle da inflamação para recuperar conforto e qualidade de vida.",
    lead: "Acompanhamento contínuo de psoríase, dermatite atópica, hidradenite supurativa e outras doenças inflamatórias crônicas da pele, em Copacabana, no Rio de Janeiro.",
    introTitle: "Doenças crônicas exigem cuidado contínuo, não soluções isoladas.",
    intro: [
      "Psoríase, dermatite atópica, hidradenite supurativa e outras doenças inflamatórias da pele são condições crônicas: alternam períodos de melhora e de atividade e podem afetar o sono, o trabalho, as relações e a autoestima. Algumas também se associam a manifestações fora da pele, como sintomas articulares, o que torna o acompanhamento contínuo mais importante do que soluções isoladas para cada crise.",
      "Vale procurar avaliação quando lesões inflamadas voltam com frequência, quando a coceira ou a dor atrapalham o dia a dia, quando surgem nódulos dolorosos em áreas de dobra ou quando o tratamento atual já não controla o quadro. O diagnóstico preciso é o ponto de partida, pois doenças diferentes podem se parecer entre si e pedem condutas distintas.",
      "A consulta avalia a extensão das lesões, os sintomas, as comorbidades e o impacto emocional, e o plano é construído em conjunto com o paciente. As opções vão de tratamentos tópicos a medicamentos sistêmicos e imunobiológicos, conforme avaliação, sempre com monitoramento da resposta e da segurança ao longo do tempo.",
    ],
    topics: [
      ["Psoríase", "Doença inflamatória imunomediada que costuma causar placas avermelhadas e descamativas, podendo afetar também unhas, couro cabeludo e articulações. A avaliação mede a extensão e o impacto do quadro para orientar a escolha entre tratamentos tópicos, sistêmicos ou outras abordagens, conforme o caso."],
      ["Dermatite atópica", "Caracteriza-se por coceira intensa, ressecamento e crises inflamatórias recorrentes, em crianças e adultos. O cuidado combina a restauração da barreira da pele, o controle da inflamação e a identificação dos fatores que desencadeiam as crises."],
      ["Hidradenite supurativa", "Doença inflamatória do folículo que provoca nódulos dolorosos, abscessos e cicatrizes em axilas, virilhas e outras áreas de dobra. O diagnóstico precoce ajuda a reduzir a progressão, e o tratamento é escalonado conforme a gravidade do quadro."],
      ["Doenças autoimunes", "Diversas doenças autoimunes apresentam manifestações na pele, que às vezes são o primeiro sinal do quadro. A investigação pode incluir exames laboratoriais e biópsia, com cuidado compartilhado com outras especialidades quando necessário."],
      ["Medicamentos imunobiológicos", "São medicamentos que atuam em alvos específicos da inflamação e podem ser indicados em quadros moderados a graves, conforme avaliação. O acompanhamento inclui triagem prévia, monitoramento da resposta e atenção contínua à segurança do tratamento."],
    ],
    process,
    doctor: "Dra. Manuela Pedretti",
    credential: "CRM-RJ 52-8115976-3 · RQE 53939",
    doctorText: "Dermatologista pela UERJ, a Dra. Manuela dedica sua atuação à psoríase, às doenças autoimunes, à dermatite atópica e à hidradenite supurativa.",
    doctorImage: "/images/dra-manuela.webp",
    faq: [
      ["Psoríase é contagiosa?", "Não. A psoríase é uma doença inflamatória imunomediada — resulta de uma resposta alterada do sistema imunológico — e não passa de uma pessoa para outra por contato, roupas ou objetos compartilhados."],
      ["Dermatite atópica tem cura?", "É uma condição crônica, que costuma alternar períodos de melhora e de crise. Embora não se fale em cura definitiva, o controle adequado pode reduzir a frequência das crises e os sintomas do dia a dia."],
      ["Hidradenite é causada por falta de higiene?", "Não. A hidradenite supurativa é uma doença inflamatória do folículo e não resulta de falta de higiene. Entender isso é importante para reduzir o estigma e buscar tratamento adequado o quanto antes."],
      ["Como funciona o acompanhamento de uma doença inflamatória crônica?", "Após o diagnóstico, os retornos são programados para avaliar a resposta ao tratamento, ajustar o plano e monitorar exames quando necessário. A frequência varia conforme a atividade da doença e o tipo de medicamento em uso."],
      ["Estresse pode piorar essas doenças?", "Fatores emocionais podem influenciar as crises em condições como psoríase e dermatite atópica, embora não sejam a causa da doença. Por isso, o cuidado também considera sono, rotina e bem-estar emocional, com apoio multidisciplinar quando indicado."],
    ],
    related: [
      ["Psoríase", "/psoriase"],
      ["Dermatite atópica", "/blog/dermatite-atopica"],
      ["Hidradenite supurativa", "/hidradenite"],
      ["Vitiligo: causas e tratamento", "/vitiligo"],
    ],
  },
  "psoriase": {
    eyebrow: "Psoríase",
    title: "Controle da psoríase para recuperar conforto, previsibilidade e qualidade de vida.",
    lead: "Da avaliação diagnóstica ao acompanhamento contínuo, a Clínica QARA oferece tratamento individualizado para psoríase em Copacabana, no Rio de Janeiro.",
    introTitle: "Tratamento integral da psoríase",
    intro: [
      "A psoríase é uma doença inflamatória crônica, mediada pelo sistema imunológico, que acelera a renovação das células da pele e forma as placas avermelhadas e descamativas características da doença. Como toda condição crônica, ela alterna períodos de melhora e de atividade, e pode acometer qualquer área do corpo — incluindo couro cabeludo, unhas e dobras —, com impacto direto no sono, no trabalho, nas relações e na autoestima.",
      "Buscar avaliação dermatológica é importante diante de placas persistentes, descamação no couro cabeludo, alterações nas unhas ou dor e inchaço nas articulações, já que a psoríase pode estar associada a artrite psoriásica e a outras comorbidades. Quanto antes o diagnóstico é confirmado, mais cedo o tratamento pode ser ajustado para controlar a inflamação e reduzir o impacto da doença no dia a dia.",
    ],
    topics: [
      ["Psoríase em placas", "É a forma mais comum da doença, caracterizada por placas avermelhadas e descamativas, geralmente nos cotovelos, joelhos, couro cabeludo e região lombar. O tratamento varia conforme a extensão e a gravidade das lesões, podendo combinar diferentes abordagens terapêuticas."],
      ["Psoríase ungueal", "Compromete a espessura, a cor e a superfície das unhas, podendo ser confundida com micose, o que exige avaliação especializada. Está frequentemente associada a maior risco de artrite psoriásica, o que reforça a importância do acompanhamento dermatológico."],
      ["Psoríase do couro cabeludo", "Causa descamação, vermelhidão e coceira que podem ser confundidas com outras condições do couro cabeludo, dificultando o diagnóstico sem avaliação especializada. O tratamento busca controlar a inflamação local sem comprometer a saúde dos fios."],
      ["Tratamentos tópicos e orais", "Para quadros leves a moderados, cremes, pomadas e medicações orais ajudam a controlar a inflamação e a velocidade de renovação da pele. A escolha e a combinação das substâncias são ajustadas conforme a resposta e a tolerância de cada paciente."],
      ["Fototerapia", "A exposição controlada à luz ultravioleta, feita em ambiente clínico, pode reduzir a atividade inflamatória em casos mais extensos ou resistentes a tratamentos tópicos. É indicada após avaliação individual, considerando o tipo de pele e o histórico do paciente."],
      ["Medicamentos biológicos injetáveis", "Para psoríase moderada a grave ou associada à artrite psoriásica, os biológicos atuam em alvos específicos da resposta imunológica, com indicação e monitoramento definidos caso a caso. A escolha do medicamento considera a extensão da doença, comorbidades e histórico de tratamentos anteriores."],
    ],
    process,
    doctor: "Dra. Manuela Pedretti",
    credential: "CRM-RJ 52-8115976-3 · RQE 53939",
    doctorText: "Dermatologista pela UERJ, a Dra. Manuela dedica sua atuação à psoríase e às doenças autoimunes, conduzindo o tratamento clínico completo — de medicações tópicas a terapias orais e biológicas injetáveis — sempre de forma individualizada.",
    doctorImage: "/images/dra-manuela.webp",
    team: [
      ["Dr. Miguel Ceccarelli", "CRM-RJ 52-0109245-6 · RQE 34414", "/images/dr-miguel.webp", "Psoríase ungueal"],
      ["Dra. Diana Stohmann", "CRM-RJ 52-1305301 · RQE 57357", "/images/dra-diana.webp", "Psoríase do couro cabeludo"],
    ],
    faq: [
      ["Psoríase é contagiosa?", "Não. A psoríase é uma doença inflamatória imunomediada — resulta de uma resposta alterada do sistema imunológico — e não passa de uma pessoa para outra por contato, roupas ou objetos compartilhados."],
      ["Psoríase tem cura?", "A psoríase é uma doença crônica, sem cura definitiva, mas com diversas opções de tratamento capazes de controlar a inflamação, reduzir as lesões e manter longos períodos de remissão. O acompanhamento contínuo permite ajustar a conduta conforme a resposta de cada paciente."],
      ["O estresse influencia a psoríase?", "Sim. Estresse emocional, infecções, uso de determinados medicamentos e traumas na pele estão entre os fatores que podem desencadear ou piorar crises de psoríase. Por isso, o manejo costuma envolver também orientações sobre hábitos e gatilhos individuais."],
      ["Psoríase nas unhas e no couro cabeludo tem tratamento específico?", "Sim. Essas formas exigem avaliação especializada, já que a resposta aos tratamentos e a técnica de aplicação variam conforme a região acometida. Por isso, a Clínica QARA conta com especialistas dedicados a cada uma dessas manifestações."],
      ["Quando os medicamentos biológicos são indicados?", "Os biológicos costumam ser considerados para casos moderados a graves, quando há comprometimento articular associado (artrite psoriásica) ou quando tratamentos tópicos e orais não trouxeram controle adequado da doença. A indicação é sempre individualizada, com avaliação de histórico clínico e exames prévios."],
    ],
    related: [
      ["Psoríase: guia para pacientes", "/blog/psoriase-guia-para-pacientes"],
      ["Hidradenite supurativa", "/hidradenite"],
      ["Vitiligo: causas e tratamento", "/vitiligo"],
      ["Psoríase e doenças inflamatórias", "/doencas-inflamatorias"],
    ],
  },
  "hidradenite": {
    eyebrow: "Hidradenite supurativa",
    title: "Tratamento clínico e cirúrgico integrado para reduzir crises, dor e cicatrizes.",
    lead: "Diagnóstico preciso e acompanhamento contínuo da hidradenite supurativa, com tratamento clínico e, quando necessário, cirúrgico, em Copacabana, no Rio de Janeiro.",
    introTitle: "Uma doença inflamatória do folículo, não uma questão de higiene.",
    intro: [
      "A hidradenite supurativa é uma doença inflamatória crônica do folículo piloso que provoca nódulos dolorosos, abscessos e, com o tempo, trajetos fistulosos e cicatrizes em áreas de dobra da pele, como axilas, virilhas, região glútea e sob as mamas. As crises costumam ser recorrentes e podem ser confundidas com furúnculos ou infecções de repetição, o que atrasa o diagnóstico correto.",
      "Na Clínica QARA, o cuidado é conduzido em equipe: a Dra. Manuela Pedretti lidera a investigação diagnóstica e o tratamento clínico, com medicações tópicas, sistêmicas e, quando indicado, imunobiológicos, enquanto o Dr. Diego Gálvez, cirurgião dermatológico, atua nos casos em que a doença já avançou para trajetos fistulosos e cicatrizes que não respondem apenas ao tratamento medicamentoso. Essa combinação permite que o plano de cada paciente seja construído conforme o estágio real da doença, sempre de forma individualizada.",
    ],
    topics: [
      ["Estágios da doença", "A hidradenite é classificada em estágios, dos nódulos isolados sem trajetos fistulosos até o comprometimento extenso com múltiplos trajetos e cicatrizes. Essa classificação orienta diretamente a escolha entre tratamento clínico, cirúrgico ou a combinação dos dois."],
      ["Tratamento clínico", "Antibióticos, anti-inflamatórios, terapias hormonais e, em quadros moderados a graves, imunobiológicos podem ser indicados conforme a extensão e a atividade da doença. O acompanhamento contínuo permite ajustar o plano e monitorar a resposta ao longo do tempo."],
      ["Tratamento cirúrgico", "Em lesões com trajetos fistulosos estabelecidos ou cicatrizes extensas, procedimentos cirúrgicos — que vão da abertura de lesões pontuais à excisão de áreas mais comprometidas — podem ser necessários quando o tratamento clínico isolado não é suficiente. A técnica e a extensão são definidas conforme cada caso."],
      ["Controle da dor", "As crises de hidradenite costumam causar dor intensa, que interfere no sono, no trabalho e nos movimentos do dia a dia. O plano de cuidado inclui estratégias para o controle da dor durante as crises, além do tratamento da inflamação de base."],
      ["Cicatrizes e trajetos fistulosos", "A doença não tratada pode evoluir para cicatrizes retráteis e trajetos que conectam lesões sob a pele, dificultando a cura e limitando o movimento em algumas áreas. Reconhecer esse padrão precocemente ajuda a definir o momento certo para avaliação cirúrgica."],
      ["Acompanhamento contínuo", "Por ser uma doença crônica e recorrente, a hidradenite pode afetar a autoestima, as relações e a rotina de trabalho. O acompanhamento a longo prazo busca reduzir a frequência das crises e devolver previsibilidade ao dia a dia do paciente."],
    ],
    process,
    doctor: "Dra. Manuela Pedretti",
    credential: "CRM-RJ 52-8115976-3 · RQE 53939",
    doctorText: "Dermatologista pela UERJ, a Dra. Manuela conduz o diagnóstico e o tratamento clínico da hidradenite supurativa, incluindo o manejo de terapias sistêmicas e imunobiológicas.",
    doctorImage: "/images/dra-manuela.webp",
    team: [
      ["Dr. Diego Gálvez", "CRM-RJ 52-0112387-4 · RQE 57517", "/images/dr-diego.webp", "Tratamento cirúrgico"],
    ],
    faq: [
      ["Hidradenite supurativa é causada por falta de higiene?", "Não. A hidradenite supurativa é uma doença inflamatória do folículo piloso, e a higiene não tem relação com sua causa. Entender isso é importante para reduzir o estigma associado à doença e buscar o tratamento adequado sem demora."],
      ["Hidradenite supurativa é contagiosa?", "Não. Apesar de as lesões poderem lembrar abscessos infecciosos, a hidradenite supurativa não é causada por um agente infeccioso e não se transmite de uma pessoa para outra."],
      ["Quando a cirurgia é indicada, em vez do tratamento clínico isolado?", "A cirurgia costuma ser considerada quando já existem trajetos fistulosos estabelecidos ou cicatrizes extensas que não respondem apenas à medicação. A decisão é sempre conjunta entre a avaliação clínica e a cirúrgica, conforme o estágio da doença."],
      ["A hidradenite pode voltar depois da cirurgia?", "Pode, especialmente se a doença permanecer ativa em outras áreas ou se o tratamento clínico de base não for mantido. Por isso, o acompanhamento clínico continua após o procedimento cirúrgico, para reduzir o risco de novas crises."],
      ["Como a hidradenite supurativa afeta a rotina do dia a dia?", "As crises podem causar dor, limitar o movimento e afetar o sono, o trabalho e a autoestima, especialmente quando a doença ainda não foi reconhecida ou tratada adequadamente. O acompanhamento contínuo busca reduzir a frequência e a intensidade das crises ao longo do tempo."],
    ],
    related: [
      ["Hidradenite supurativa: sintomas e tratamento", "/blog/hidradenite-supurativa"],
      ["Psoríase", "/psoriase"],
      ["Cirurgia dermatológica", "/cirurgia-dermatologica"],
      ["Psoríase e doenças inflamatórias", "/doencas-inflamatorias"],
    ],
  },
  "vitiligo": {
    eyebrow: "Vitiligo",
    title: "Tratamento clínico e cirúrgico para recuperar a cor da pele.",
    lead: "Diagnóstico preciso e acompanhamento contínuo do vitiligo, do tratamento clínico à cirurgia de repigmentação em casos estáveis selecionados, em Copacabana, no Rio de Janeiro.",
    introTitle: "Cada fase do vitiligo pede uma abordagem diferente.",
    intro: [
      "O vitiligo é uma doença autoimune: o sistema imunológico ataca os melanócitos, as células responsáveis pela produção de melanina, o pigmento que dá cor à pele. Esse processo resulta em manchas brancas bem definidas, que podem surgir em qualquer área do corpo, isoladas ou em grupos, e evoluir de forma imprevisível ao longo do tempo.",
      "O vitiligo não é contagioso e não é causado apenas por questões emocionais, embora fatores como o estresse possam, em algumas pessoas, coincidir com períodos de maior atividade da doença. Manchas que surgem ou aumentam rapidamente indicam atividade e merecem avaliação sem demora, pois o período de estabilização — quando a doença deixa de progredir — influencia diretamente a resposta ao tratamento, inclusive a possibilidade de procedimentos cirúrgicos no futuro.",
      "Na Clínica QARA, em Copacabana, o cuidado do vitiligo é conduzido em duas frentes complementares. O tratamento clínico — com medicação tópica, fototerapia e, em casos selecionados, terapia sistêmica — é a base da abordagem e busca estabilizar a doença e repigmentar as áreas afetadas. Para pacientes com vitiligo estável que não respondeu totalmente ao tratamento clínico, a cirurgia dermatológica pode ser uma opção em áreas específicas, sempre após avaliação individualizada.",
    ],
    topics: [
      ["Diagnóstico e classificação", "O exame clínico, muitas vezes auxiliado pela luz de Wood, identifica a extensão, o padrão e a atividade das manchas, diferenciando o vitiligo de outras causas de despigmentação da pele. Essa classificação orienta a escolha entre as opções de tratamento clínico e cirúrgico."],
      ["Tratamento tópico e imunomodulador", "Corticosteroides e imunomoduladores tópicos ajudam a controlar a resposta imunológica local e podem favorecer a repigmentação em áreas selecionadas. A escolha do produto, a área tratada e o tempo de uso são definidos conforme a localização e a extensão das manchas."],
      ["Fototerapia (NB-UVB)", "A fototerapia com UVB de banda estreita estimula os melanócitos remanescentes e é uma das abordagens mais utilizadas no tratamento do vitiligo. A resposta costuma ser gradual, e a frequência das sessões é ajustada conforme a evolução observada ao longo do acompanhamento."],
      ["Terapia sistêmica", "Em quadros com atividade importante ou maior extensão, medicações sistêmicas podem ser indicadas para ajudar a conter a progressão da doença. A indicação considera o histórico do paciente, a extensão do vitiligo e a resposta a tratamentos anteriores."],
      ["Cirurgia para vitiligo estável", "Técnicas cirúrgicas de transplante autólogo de melanócitos, como o mini-enxerto (mini-punch grafting), podem ser indicadas para áreas localizadas de vitiligo estável — sem atividade por um período definido — que não respondeu de forma satisfatória ao tratamento clínico isolado. É uma opção especializada, reservada a casos selecionados após avaliação criteriosa, e nunca indicada para doença em atividade."],
      ["Impacto emocional e qualidade de vida", "As manchas visíveis do vitiligo podem afetar a autoestima e as relações sociais, independentemente da extensão do quadro. O acompanhamento considera esse impacto e pode incluir orientação sobre camuflagem e apoio psicológico, quando indicado."],
    ],
    process,
    doctor: "Dra. Manuela Pedretti",
    credential: "CRM-RJ 52-8115976-3 · RQE 53939",
    doctorText: "Dermatologista pela UERJ, a Dra. Manuela dedica sua atuação às doenças autoimunes da pele e conduz o tratamento clínico do vitiligo, do diagnóstico ao acompanhamento da resposta terapêutica.",
    doctorImage: "/images/dra-manuela.webp",
    team: [
      ["Dr. Diego Gálvez", "CRM-RJ 52-0112387-4 · RQE 57517", "/images/dr-diego.webp", "Tratamento cirúrgico"],
    ],
    faq: [
      ["Vitiligo é contagioso ou causado só por estresse?", "Não. O vitiligo é uma doença autoimune — resulta de uma resposta alterada do sistema imunológico contra os melanócitos — e não passa de uma pessoa para outra. Fatores emocionais podem influenciar períodos de atividade em algumas pessoas, mas não são a causa da doença."],
      ["O vitiligo tem cura?", "Não existe cura definitiva, mas é possível estabilizar a doença e repigmentar total ou parcialmente muitas das áreas afetadas, conforme o tratamento e a resposta de cada paciente. Os resultados variam de acordo com a região do corpo, o tempo de doença e a extensão das manchas."],
      ["Quando a cirurgia é uma opção para o vitiligo?", "Apenas para manchas estáveis — sem atividade por um período definido, avaliado pelo médico — que não responderam de forma satisfatória ao tratamento clínico isolado. A cirurgia não é indicada para vitiligo em atividade ou em fase de espalhamento rápido, e a maior parte dos pacientes é tratada por via clínica."],
      ["Quanto tempo leva para ver resultado no tratamento?", "A resposta ao tratamento clínico costuma ser gradual, muitas vezes observada ao longo de vários meses de acompanhamento contínuo. O tempo varia conforme a área tratada, a extensão do quadro e o tipo de tratamento escolhido."],
      ["As áreas com vitiligo precisam de cuidado especial com o sol?", "Sim. A pele sem pigmento tem menos proteção natural contra a radiação solar e queima com mais facilidade, por isso o uso de protetor solar nas áreas afetadas é reforçado no plano de cuidado. A proteção também ajuda a reduzir o contraste entre a pele com e sem manchas."],
    ],
    related: [
      ["Vitiligo: causas e tratamento", "/blog/vitiligo-causas-e-tratamento"],
      ["Psoríase e doenças inflamatórias", "/doencas-inflamatorias"],
      ["Cirurgia dermatológica", "/cirurgia-dermatologica"],
    ],
  },
  "dermatopediatria": {
    eyebrow: "Dermatopediatria",
    title: "Cuidado dermatológico para bebês, crianças e adolescentes.",
    lead: "Avaliação acolhedora das doenças da pele na infância e na adolescência, com orientações práticas para toda a família, em Copacabana, no Rio de Janeiro.",
    introTitle: "A pele da criança muda com a idade.",
    intro: [
      "A pele da criança muda do nascimento à adolescência, e condições comuns podem ter aparência, evolução e tratamentos diferentes dos observados em adultos. Assaduras persistentes, marcas de nascimento, dermatite atópica, micoses e acne estão entre as queixas mais frequentes, e cada fase da vida exige um olhar específico sobre a segurança e a forma de usar os tratamentos.",
      "Vale procurar a dermatopediatria quando uma lesão persiste, cresce ou muda de aspecto, quando a coceira atrapalha o sono e a escola, quando há crises repetidas de pele seca e inflamada ou quando existe dúvida sobre uma marca de nascimento. O acompanhamento também ajuda adolescentes com acne a controlar a inflamação e prevenir cicatrizes.",
      "A consulta é pensada para ser acolhedora: o exame respeita o tempo da criança, e a conversa envolve os responsáveis. Além do diagnóstico, o plano inclui orientações práticas sobre banho, hidratação e produtos adequados à idade, com retornos programados para acompanhar a evolução e ajustar o cuidado conforme o crescimento.",
    ],
    topics: [
      ["Dermatite atópica", "Uma das condições mais comuns da infância, causa pele seca, coceira e crises inflamatórias que podem atrapalhar o sono. O cuidado combina rotina de hidratação, controle das crises e orientações à família para reduzir recaídas."],
      ["Infecções e micoses", "Infecções bacterianas, virais e fúngicas são frequentes na infância e podem se confundir com outras doenças da pele. A avaliação confirma o diagnóstico — com exames quando necessário — e orienta o tratamento e os cuidados para evitar transmissão."],
      ["Pintas e marcas de nascimento", "Nevos, manchas e lesões vasculares são avaliados quanto a tamanho, localização e evolução. Muitos casos exigem apenas observação, mas alguns se beneficiam de acompanhamento próximo ou de tratamento precoce, conforme avaliação."],
      ["Acne na adolescência", "A acne costuma começar na puberdade e pode deixar marcas físicas e emocionais quando não tratada. O plano busca controlar a inflamação de forma adequada à idade e prevenir cicatrizes, com acompanhamento da resposta ao longo do tempo."],
      ["Doenças de cabelo e unhas", "Queda de cabelo, falhas no couro cabeludo e alterações das unhas têm causas próprias da infância e da adolescência. A investigação diferencia quadros transitórios de condições que precisam de tratamento específico."],
      ["Psoríase infantil", "A psoríase também ocorre em crianças, às vezes com apresentação diferente da observada em adultos. O diagnóstico cuidadoso e a escolha terapêutica adaptada à idade permitem controlar o quadro com segurança e acompanhar o impacto na rotina."],
    ],
    process,
    doctor: "Dr. Fabrício de Andrade",
    credential: "CRM-RJ 92.788-0",
    doctorText: "Dermatologista formado no Instituto Professor Rubem David Azulay, com formação também em Pediatria e Terapia Intensiva Pediátrica pelo Hospital Prontobaby. O Dr. Fabrício atende às terças-feiras, das 14h às 20h; quartas-feiras, das 10h às 20h; e quintas-feiras, das 10h às 14h.",
    doctorImage: "/images/dr-fabricio-de-andrade.webp",
    faq: [
      ["Crianças podem usar os mesmos medicamentos dos adultos?", "Nem sempre. Dose, veículo (creme, pomada ou loção), área tratada e perfil de segurança variam conforme a idade e o peso. Por isso, a prescrição em dermatopediatria é sempre individualizada."],
      ["Quando uma mancha de nascimento precisa ser avaliada?", "Quando é extensa, muda de tamanho ou de cor, causa sintomas ou gera dúvida diagnóstica. Mesmo marcas aparentemente simples podem se beneficiar de uma avaliação inicial para definir se há necessidade de acompanhamento."],
      ["A consulta orienta cuidados diários?", "Sim. Orientações sobre banho, hidratação, escolha de produtos adequados à idade e prevenção de crises fazem parte do plano de cuidado, com instruções práticas para a rotina da família."],
      ["A partir de que idade a criança pode ir ao dermatologista?", "Não há idade mínima: bebês podem ser avaliados desde os primeiros dias de vida quando há alterações na pele. Muitas condições do recém-nascido são benignas e transitórias, e a consulta ajuda a diferenciá-las das que precisam de tratamento."],
      ["Preciso levar algo para a consulta do meu filho?", "Leve a caderneta ou os registros de saúde, a lista de produtos e medicamentos já utilizados e, se possível, fotos das lesões nos momentos de crise. Essas informações ajudam quando o quadro varia e nem sempre está visível no dia da consulta."],
    ],
    related: [
      ["Dermatite atópica no bebê", "/blog/dermatite-atopica-no-bebe"],
      ["Acne na adolescência", "/blog/acne-na-adolescencia"],
      ["Marcas de nascimento", "/blog/marcas-de-nascimento-quando-avaliar"],
    ],
  },
  "dermatologia-estetica": {
    eyebrow: "Dermatologia estética",
    title: "Naturalidade começa com um plano individualizado.",
    lead: "Procedimentos dermatológicos planejados a partir da anatomia, da saúde da pele e dos objetivos de cada paciente, em Copacabana, no Rio de Janeiro.",
    introTitle: "A melhor indicação depende do que realmente precisa ser tratado.",
    intro: [
      "Textura irregular, manchas, cicatrizes de acne, flacidez e sinais do envelhecimento exigem estratégias diferentes — e nem todo procedimento serve para todo caso. Na dermatologia estética, o ponto de partida não é a técnica, e sim o diagnóstico: entender o que de fato precisa ser tratado na pele de cada paciente para, então, escolher a abordagem mais adequada, com segurança e naturalidade.",
      "Vale procurar avaliação quando algum aspecto da pele incomoda de forma consistente, quando há dúvida sobre qual procedimento faz sentido ou quando tratamentos anteriores não trouxeram o resultado esperado. A avaliação médica também identifica condições de pele que precisam ser tratadas antes de qualquer procedimento estético.",
      "A consulta começa com o exame da pele e uma conversa sobre objetivos, histórico de saúde e expectativas. O dermatologista explica benefícios, limitações, riscos e tempo de recuperação de cada opção antes de qualquer decisão, e o plano pode ser dividido em etapas, com reavaliações para acompanhar a resposta da pele ao longo do tratamento.",
    ],
    topics: [
      ["Textura e sinais do envelhecimento", "Poros dilatados, linhas finas, perda de luminosidade e flacidez inicial podem ser abordados com procedimentos que estimulam a produção de colágeno, conforme avaliação. A escolha depende do tipo de pele, da queixa principal e do tempo de recuperação aceitável para cada paciente."],
      ["Manchas", "Melasma, manchas solares e outras hiperpigmentações têm origens e profundidades diferentes, o que muda a conduta. A avaliação do tipo de pigmentação precede a indicação de peelings, laser ou tratamentos tópicos, sempre associada a orientações de proteção solar."],
      ["Cicatrizes de acne", "As cicatrizes variam em tipo e profundidade, e é comum que um mesmo paciente apresente mais de um padrão. O tratamento costuma combinar técnicas em sessões planejadas, com expectativa realista de melhora gradual ao longo do tempo."],
      ["Toxina botulínica", "Utilizada no tratamento de rugas dinâmicas — as que aparecem com o movimento da face — e em outras indicações dermatológicas avaliadas em consulta. O planejamento considera a anatomia e a expressão de cada rosto, buscando um resultado equilibrado."],
      ["Preenchimentos", "Repõem volume ou oferecem suporte estrutural em áreas selecionadas, a partir de planejamento anatômico individualizado. A consulta discute indicações, limites e durabilidade esperada, priorizando segurança e harmonia com as características do paciente."],
      ["Procedimentos cirúrgicos", "Blefaroplastia (cirurgia das pálpebras), correção de cicatrizes e outros procedimentos selecionados podem ser indicados após avaliação criteriosa. O paciente recebe orientações detalhadas sobre preparo, recuperação e cuidados após a cirurgia."],
    ],
    process,
    doctor: "Dr. Miguel Ceccarelli",
    credential: "CRM-RJ 52-0109245-6 · RQE 34414",
    doctorText: "Dermatologista com atuação em dermatologia estética, o Dr. Miguel conduz cada indicação a partir de um planejamento individualizado, alinhado à anatomia e aos objetivos do paciente.",
    doctorImage: "/images/dr-miguel.webp",
    faq: [
      ["O resultado fica natural?", "O planejamento busca equilíbrio e respeito às características de cada rosto e de cada pele, evitando excessos. Ainda assim, os resultados variam de pessoa para pessoa, e as expectativas são alinhadas antes de qualquer procedimento."],
      ["Todo procedimento exige afastamento das atividades?", "Não. Alguns permitem retorno imediato à rotina, enquanto outros pedem alguns dias de recuperação. O tempo esperado para cada técnica é explicado na consulta, para que o paciente possa se programar."],
      ["É possível combinar tratamentos?", "Em alguns casos, sim. A combinação pode ser útil quando as queixas têm causas diferentes, mas a sequência e o intervalo entre as sessões devem ser definidos pelo médico, conforme a resposta da pele."],
      ["Preciso de avaliação antes de agendar um procedimento?", "Sim. A consulta de avaliação define se o procedimento é adequado ao seu caso, esclarece riscos e alternativas e permite planejar etapas e intervalos com segurança. É nela que o plano de tratamento é construído."],
      ["Quem tem melasma ou pele sensível pode fazer procedimentos?", "Muitas vezes sim, mas a escolha da técnica e dos parâmetros precisa considerar o risco de manchas e de irritação. Em alguns casos, a pele é preparada antes, e o tratamento avança de forma mais gradual, conforme avaliação."],
    ],
    related: [
      ["Melasma: por que as manchas voltam", "/blog/melasma-por-que-as-manchas-voltam"],
      ["Toxina botulínica: o que avaliar antes", "/blog/toxina-botulinica-antes-de-aplicar"],
      ["Preenchimento facial: o planejamento", "/blog/preenchimento-facial-planejamento"],
      ["Cicatrizes de acne", "/blog/cicatrizes-de-acne-tratamento"],
    ],
  },
};
