import type { Specialty } from "./specialty-template";

const process: [string, string][] = [
  ["Escuta e histórico", "Conversa detalhada sobre os sintomas, o tempo de evolução, os tratamentos já realizados e o impacto na rotina."],
  ["Exame dermatológico", "Avaliação dirigida da pele, dos cabelos ou das unhas, com dermatoscopia quando indicada."],
  ["Investigação", "Exames laboratoriais, cultura, exame micológico ou biópsia apenas quando contribuem para o diagnóstico."],
  ["Plano de cuidado", "Tratamento individualizado, orientações práticas e acompanhamento da resposta ao longo do tempo."],
];

export const specialties: Record<string, Specialty> = {
  "dermatologia-clinica": {
    eyebrow: "Dermatologia clínica",
    title: "Cuidado completo para a saúde da pele.",
    lead: "Avaliação e acompanhamento de doenças da pele, dos cabelos e das unhas em adultos, com diagnóstico cuidadoso e plano individualizado, em Copacabana, no Rio de Janeiro.",
    introTitle: "A pele pode revelar condições locais e sistêmicas.",
    intro: [
      "Coceira que não passa, manchas novas, feridas que demoram a cicatrizar, acne, queda de cabelo e outras alterações persistentes podem ter causas muito diferentes entre si. A dermatologia clínica organiza esses sinais: identifica padrões, diferencia condições parecidas e define quando exames complementares realmente acrescentam informação. A pele também pode refletir doenças internas, e a avaliação dermatológica costuma ser o primeiro passo dessa investigação.",
      "Vale procurar avaliação quando uma alteração persiste por semanas, muda de aspecto, causa dor, coceira ou sangramento, ou quando interfere no sono, no trabalho e na autoestima. Também costuma ser recomendável manter consultas de rotina para exame das pintas, especialmente para pessoas de pele clara, com histórico familiar de câncer da pele ou grande exposição solar acumulada — uma realidade comum no Rio de Janeiro.",
      "Na Clínica QARA, em Copacabana, a consulta começa com escuta detalhada e exame completo da pele, dos cabelos e das unhas, com dermatoscopia quando indicada. A partir daí, o dermatologista explica as hipóteses diagnósticas, solicita exames apenas quando necessários e constrói um plano de tratamento compatível com a rotina do paciente, com retornos programados para acompanhar a resposta.",
    ],
    topics: [
      ["Acne e rosácea", "Condições inflamatórias frequentes que causam lesões, vermelhidão persistente e, com o tempo, marcas e cicatrizes. A avaliação identifica o tipo e a gravidade do quadro para definir um tratamento em etapas, com acompanhamento da resposta."],
      ["Manchas e pigmentação", "Melasma, hiperpigmentação pós-inflamatória e outras alterações de cor têm causas e comportamentos distintos. O exame avalia o padrão, a profundidade e a evolução do pigmento antes de definir a estratégia de tratamento e de proteção solar."],
      ["Infecções da pele", "Micoses, infecções bacterianas e virais podem se parecer com outras doenças da pele. Quando há dúvida, exames como o micológico direto e a cultura ajudam a confirmar o diagnóstico antes de iniciar o tratamento adequado."],
      ["Alergias e coceira", "Dermatites de contato, urticária e outras causas de prurido (coceira) exigem investigação cuidadosa do histórico e dos fatores desencadeantes. O plano combina o alívio dos sintomas com a identificação e o afastamento da causa, quando possível."],
      ["Pintas e lesões", "Nevos (pintas), lesões novas ou que mudaram de cor, tamanho ou formato merecem exame clínico e dermatoscópico. A dermatoscopia amplia a imagem da lesão e ajuda a decidir entre acompanhamento, biópsia ou remoção."],
      ["Doenças crônicas", "Condições recorrentes, como eczemas e outras dermatoses de longa duração, pedem acompanhamento contínuo, e não apenas o tratamento das crises. O seguimento permite ajustar o plano conforme a resposta e prevenir complicações."],
    ],
    process,
    doctor: "Dr. Diego Gálvez",
    credential: "CRM-RJ 52-0112387-4 · RQE 57517",
    doctorText: "Dermatologista com atuação clínica e cirúrgica, o Dr. Diego acompanha pacientes em consultas presenciais na clínica e também por telemedicina.",
    doctorImage: "/images/dr-diego.webp",
    faq: [
      ["Quando devo procurar um dermatologista?", "Quando uma alteração da pele, do cabelo ou das unhas persiste por semanas, causa sintomas, muda rapidamente de aspecto ou interfere na qualidade de vida. Consultas de rotina para exame das pintas também costumam ser recomendadas, conforme o perfil de risco de cada pessoa."],
      ["A consulta inclui dermatoscopia?", "A dermatoscopia — exame com uma lente especial que amplia as estruturas da pele — pode ser utilizada quando ajuda na avaliação de pintas, lesões e outras condições. A indicação é feita pelo próprio médico durante a consulta."],
      ["É possível fazer consulta online?", "Alguns quadros e retornos de acompanhamento podem ser avaliados por telemedicina. Outros exigem exame presencial, como a avaliação de pintas e lesões suspeitas; em caso de dúvida, a equipe orienta qual formato é mais adequado para a sua situação."],
      ["Como me preparo para a consulta dermatológica?", "Se possível, compareça com a pele limpa, sem maquiagem e com as unhas sem esmalte, e leve a lista de medicamentos em uso e exames anteriores. Anotar quando a alteração começou e o que já foi tentado também ajuda a avaliação."],
      ["Quais sinais em uma pinta merecem avaliação mais rápida?", "Pintas que mudam de cor, tamanho ou formato, têm bordas irregulares, coçam, sangram ou se destacam das demais devem ser avaliadas sem demora. Feridas que não cicatrizam em algumas semanas também merecem exame dermatológico."],
    ],
    related: [
      ["Câncer da pele: sinais de alerta", "/blog/cancer-da-pele-sinais-de-alerta"],
      ["Quando a biópsia é indicada", "/blog/biopsia-de-pele-quando-e-indicada"],
    ],
  },
  "unhas": {
    eyebrow: "Dermatologia das unhas",
    title: "Unhas saudáveis começam com um diagnóstico preciso.",
    lead: "Avaliação especializada de alterações de cor, formato, espessura, dor e inflamação das unhas, com investigação diagnóstica dedicada, em Copacabana, no Rio de Janeiro.",
    introTitle: "Nem toda alteração da unha é micose.",
    intro: [
      "As unhas podem mudar de cor, formato ou espessura por muitos motivos: traumas repetidos, micoses, psoríase, doenças inflamatórias, medicamentos e até condições sistêmicas. Como quadros diferentes produzem alterações parecidas, tratar sem confirmar a causa pode significar meses de tratamento sem resultado. A dermatologia das unhas é a área dedicada a investigar e cuidar da unidade ungueal — a unha e as estruturas que a formam.",
      "Vale procurar avaliação quando uma alteração persiste ou avança, quando há dor, inflamação ou secreção ao redor da unha, quando surge uma faixa escura nova ou quando tratamentos anteriores não funcionaram. Alterações em uma única unha, em especial, merecem atenção, pois podem indicar causas locais que exigem exame dirigido.",
      "Na consulta, o dermatologista examina todas as unhas e a pele ao redor, com dermatoscopia quando indicada, e pode coletar material para exame micológico ou cultura. Em casos selecionados, a biópsia da unidade ungueal esclarece o diagnóstico. Definida a causa, o plano pode incluir tratamento clínico, cuidados locais ou procedimento cirúrgico, conforme avaliação.",
    ],
    topics: [
      ["Micose das unhas", "A onicomicose (micose das unhas) causa espessamento, descolamento e mudança de cor, mas outras doenças produzem sinais parecidos. Por isso, a confirmação por exame micológico, cultura ou análise da lâmina costuma preceder o tratamento, escolhido conforme a extensão do quadro."],
      ["Unha encravada", "Ocorre quando a borda da unha penetra a pele ao redor, causando dor, inflamação e, às vezes, infecção. A avaliação define se o quadro pode ser resolvido com medidas clínicas e correção do corte ou se há indicação de procedimento cirúrgico, sobretudo em casos recorrentes."],
      ["Psoríase ungueal", "A psoríase pode afetar as unhas causando pequenos furos (pitting), descolamento, espessamento e manchas, mesmo quando há pouca lesão na pele. O reconhecimento correto evita tratamentos antifúngicos desnecessários e direciona o cuidado para o controle da inflamação."],
      ["Tumores ungueais", "Nódulos, faixas pigmentadas e lesões persistentes sob a unha ou ao redor dela exigem investigação criteriosa, que vai de tumores benignos a lesões que precisam de biópsia. A dermatoscopia e, quando indicado, o exame histológico orientam a conduta."],
      ["Fragilidade e distrofias", "Unhas quebradiças, descamativas, deformadas ou com crescimento alterado podem refletir hábitos, contato com produtos químicos, envelhecimento ou doenças de base. A avaliação busca a causa e orienta cuidados de proteção e tratamento conforme cada caso."],
      ["Cirurgia da unha", "Biópsias, correção de unha encravada e remoção de lesões da unidade ungueal são procedimentos realizados com técnica e anestesia adequadas à região. A indicação é sempre individualizada, considerando diagnóstico, sintomas e recorrência."],
    ],
    process,
    doctor: "Dr. Miguel Ceccarelli",
    credential: "CRM-RJ 52-1092456 · RQE 34414",
    doctorText: "Dermatologista com atuação dedicada às doenças das unhas, o Dr. Miguel conduz a investigação diagnóstica e realiza os procedimentos da unidade ungueal quando indicados.",
    doctorImage: "/images/dr-miguel.webp",
    faq: [
      ["Toda unha amarelada é micose?", "Não. Psoríase, traumas repetidos e outras doenças podem causar alterações muito semelhantes às da micose. Por isso, exames como o micológico direto e a cultura podem ser necessários antes de iniciar qualquer tratamento."],
      ["Unha encravada sempre precisa de cirurgia?", "Não. Muitos casos melhoram com medidas clínicas e correção da forma de cortar a unha. A indicação cirúrgica depende da intensidade da inflamação, da recorrência e da anatomia da unha, avaliadas em consulta."],
      ["Faixa escura na unha precisa ser avaliada?", "Sim, especialmente se for nova, estiver mudando ou vier acompanhada de pigmentação na pele ao redor. Muitas faixas têm causa benigna, mas a avaliação dermatológica com dermatoscopia ajuda a identificar os casos que exigem investigação adicional."],
      ["Preciso tirar o esmalte antes da consulta?", "Sim. O ideal é remover esmaltes e alongamentos de todas as unhas alguns dias antes, pois a cobertura pode esconder alterações importantes. Isso também permite a coleta de material para exames, se houver necessidade."],
      ["Quanto tempo dura o tratamento da micose de unha?", "O tempo varia conforme a unha acometida e a extensão do quadro, e costuma acompanhar o crescimento lento da unha — em geral, vários meses. O acompanhamento periódico permite verificar a resposta e ajustar o plano quando necessário."],
    ],
    related: [
      ["Doenças das unhas", "/blog/doencas-das-unhas"],
      ["Psoríase", "/blog/psoriase-guia-para-pacientes"],
    ],
  },
  "doencas-inflamatorias": {
    eyebrow: "Psoríase e doenças inflamatórias",
    title: "Controle da inflamação para recuperar conforto e qualidade de vida.",
    lead: "Acompanhamento contínuo de psoríase, dermatite atópica, hidradenite supurativa e outras doenças inflamatórias crônicas da pele, em Copacabana, no Rio de Janeiro.",
    introTitle: "Doenças crônicas exigem cuidado contínuo, não soluções isoladas.",
    intro: [
      "Psoríase, dermatite atópica, hidradenite supurativa e outras doenças inflamatórias da pele são condições crônicas: alternam períodos de melhora e de atividade e podem afetar o sono, o trabalho, as relações e a autoestima. Algumas também se associam a manifestações fora da pele, como sintomas articulares, o que torna o acompanhamento contínuo mais importante do que soluções isoladas para cada crise.",
      "Vale procurar avaliação quando lesões inflamadas voltam com frequência, quando a coceira ou a dor atrapalham o dia a dia, quando surgem nódulos dolorosos em áreas de dobra ou quando o tratamento atual já não controla o quadro. O diagnóstico preciso é o ponto de partida, pois doenças diferentes podem se parecer entre si e pedem condutas distintas.",
      "A consulta avalia a extensão das lesões, os sintomas, as comorbidades e o impacto emocional, e o plano é construído em conjunto com o paciente. As opções vão de tratamentos tópicos a medicamentos sistêmicos e imunobiológicos, conforme avaliação, sempre com monitoramento da resposta e da segurança ao longo do tempo.",
    ],
    topics: [
      ["Psoríase", "Doença inflamatória imunomediada que costuma causar placas avermelhadas e descamativas, podendo afetar também unhas, couro cabeludo e articulações. A avaliação mede a extensão e o impacto do quadro para orientar a escolha entre tratamentos tópicos, sistêmicos ou outras abordagens, conforme o caso."],
      ["Dermatite atópica", "Caracteriza-se por coceira intensa, ressecamento e crises inflamatórias recorrentes, em crianças e adultos. O cuidado combina a restauração da barreira da pele, o controle da inflamação e a identificação dos fatores que desencadeiam as crises."],
      ["Hidradenite supurativa", "Doença inflamatória do folículo que provoca nódulos dolorosos, abscessos e cicatrizes em axilas, virilhas e outras áreas de dobra. O diagnóstico precoce ajuda a reduzir a progressão, e o tratamento é escalonado conforme a gravidade do quadro."],
      ["Doenças autoimunes", "Diversas doenças autoimunes apresentam manifestações na pele, que às vezes são o primeiro sinal do quadro. A investigação pode incluir exames laboratoriais e biópsia, com cuidado compartilhado com outras especialidades quando necessário."],
      ["Medicamentos imunobiológicos", "São medicamentos que atuam em alvos específicos da inflamação e podem ser indicados em quadros moderados a graves, conforme avaliação. O acompanhamento inclui triagem prévia, monitoramento da resposta e atenção contínua à segurança do tratamento."],
      ["Dermatopediatria inflamatória", "Doenças inflamatórias também acontecem na infância e pedem abordagem adaptada à idade, à família e à rotina escolar. O plano considera a segurança dos tratamentos em cada faixa etária e traz orientações práticas para os cuidadores."],
    ],
    process,
    doctor: "Dra. Manuela Pedretti",
    credential: "CRM-RJ 52-8115976-3 · RQE 53939",
    doctorText: "Dermatologista pela UERJ, a Dra. Manuela dedica sua atuação à psoríase, às doenças autoimunes, à dermatite atópica e à dermatopediatria.",
    doctorImage: "/images/dra-manuela.webp",
    faq: [
      ["Psoríase é contagiosa?", "Não. A psoríase é uma doença inflamatória imunomediada — resulta de uma resposta alterada do sistema imunológico — e não passa de uma pessoa para outra por contato, roupas ou objetos compartilhados."],
      ["Dermatite atópica tem cura?", "É uma condição crônica, que costuma alternar períodos de melhora e de crise. Embora não se fale em cura definitiva, o controle adequado pode reduzir a frequência das crises e os sintomas do dia a dia."],
      ["Hidradenite é causada por falta de higiene?", "Não. A hidradenite supurativa é uma doença inflamatória do folículo e não resulta de falta de higiene. Entender isso é importante para reduzir o estigma e buscar tratamento adequado o quanto antes."],
      ["Como funciona o acompanhamento de uma doença inflamatória crônica?", "Após o diagnóstico, os retornos são programados para avaliar a resposta ao tratamento, ajustar o plano e monitorar exames quando necessário. A frequência varia conforme a atividade da doença e o tipo de medicamento em uso."],
      ["Estresse pode piorar essas doenças?", "Fatores emocionais podem influenciar as crises em condições como psoríase e dermatite atópica, embora não sejam a causa da doença. Por isso, o cuidado também considera sono, rotina e bem-estar emocional, com apoio multidisciplinar quando indicado."],
    ],
    related: [
      ["Psoríase", "/blog/psoriase-guia-para-pacientes"],
      ["Dermatite atópica", "/blog/dermatite-atopica"],
      ["Hidradenite supurativa", "/blog/hidradenite-supurativa"],
    ],
  },
  "dermatopediatria": {
    eyebrow: "Dermatopediatria",
    title: "Cuidado dermatológico para bebês, crianças e adolescentes.",
    lead: "Avaliação acolhedora das doenças da pele na infância e na adolescência, com orientações práticas para toda a família, em Copacabana, no Rio de Janeiro.",
    introTitle: "A pele da criança muda com a idade.",
    intro: [
      "A pele da criança muda do nascimento à adolescência, e condições comuns podem ter aparência, evolução e tratamentos diferentes dos observados em adultos. Assaduras persistentes, marcas de nascimento, dermatite atópica, micoses e acne estão entre as queixas mais frequentes, e cada fase da vida exige um olhar específico sobre a segurança e a forma de usar os tratamentos.",
      "Vale procurar a dermatopediatria quando uma lesão persiste, cresce ou muda de aspecto, quando a coceira atrapalha o sono e a escola, quando há crises repetidas de pele seca e inflamada ou quando existe dúvida sobre uma marca de nascimento. O acompanhamento também ajuda adolescentes com acne a controlar a inflamação e prevenir cicatrizes.",
      "A consulta é pensada para ser acolhedora: o exame respeita o tempo da criança, e a conversa envolve os responsáveis. Além do diagnóstico, o plano inclui orientações práticas sobre banho, hidratação e produtos adequados à idade, com retornos programados para acompanhar a evolução e ajustar o cuidado conforme o crescimento.",
    ],
    topics: [
      ["Dermatite atópica", "Uma das condições mais comuns da infância, causa pele seca, coceira e crises inflamatórias que podem atrapalhar o sono. O cuidado combina rotina de hidratação, controle das crises e orientações à família para reduzir recaídas."],
      ["Infecções e micoses", "Infecções bacterianas, virais e fúngicas são frequentes na infância e podem se confundir com outras doenças da pele. A avaliação confirma o diagnóstico — com exames quando necessário — e orienta o tratamento e os cuidados para evitar transmissão."],
      ["Pintas e marcas de nascimento", "Nevos, manchas e lesões vasculares são avaliados quanto a tamanho, localização e evolução. Muitos casos exigem apenas observação, mas alguns se beneficiam de acompanhamento próximo ou de tratamento precoce, conforme avaliação."],
      ["Acne na adolescência", "A acne costuma começar na puberdade e pode deixar marcas físicas e emocionais quando não tratada. O plano busca controlar a inflamação de forma adequada à idade e prevenir cicatrizes, com acompanhamento da resposta ao longo do tempo."],
      ["Doenças de cabelo e unhas", "Queda de cabelo, falhas no couro cabeludo e alterações das unhas têm causas próprias da infância e da adolescência. A investigação diferencia quadros transitórios de condições que precisam de tratamento específico."],
      ["Psoríase infantil", "A psoríase também ocorre em crianças, às vezes com apresentação diferente da observada em adultos. O diagnóstico cuidadoso e a escolha terapêutica adaptada à idade permitem controlar o quadro com segurança e acompanhar o impacto na rotina."],
    ],
    process,
    doctor: "Dra. Manuela Pedretti",
    credential: "CRM-RJ 52-8115976-3 · RQE 53939",
    doctorText: "Dermatologista com residência pela UERJ, a Dra. Manuela atua em dermatopediatria e doenças inflamatórias, acompanhando crianças e adolescentes junto às suas famílias.",
    doctorImage: "/images/dra-manuela.webp",
    faq: [
      ["Crianças podem usar os mesmos medicamentos dos adultos?", "Nem sempre. Dose, veículo (creme, pomada ou loção), área tratada e perfil de segurança variam conforme a idade e o peso. Por isso, a prescrição em dermatopediatria é sempre individualizada."],
      ["Quando uma mancha de nascimento precisa ser avaliada?", "Quando é extensa, muda de tamanho ou de cor, causa sintomas ou gera dúvida diagnóstica. Mesmo marcas aparentemente simples podem se beneficiar de uma avaliação inicial para definir se há necessidade de acompanhamento."],
      ["A consulta orienta cuidados diários?", "Sim. Orientações sobre banho, hidratação, escolha de produtos adequados à idade e prevenção de crises fazem parte do plano de cuidado, com instruções práticas para a rotina da família."],
      ["A partir de que idade a criança pode ir ao dermatologista?", "Não há idade mínima: bebês podem ser avaliados desde os primeiros dias de vida quando há alterações na pele. Muitas condições do recém-nascido são benignas e transitórias, e a consulta ajuda a diferenciá-las das que precisam de tratamento."],
      ["Preciso levar algo para a consulta do meu filho?", "Leve a caderneta ou os registros de saúde, a lista de produtos e medicamentos já utilizados e, se possível, fotos das lesões nos momentos de crise. Essas informações ajudam quando o quadro varia e nem sempre está visível no dia da consulta."],
    ],
    related: [
      ["Dermatite atópica", "/blog/dermatite-atopica"],
      ["Psoríase", "/blog/psoriase-guia-para-pacientes"],
    ],
  },
  "dermatologia-estetica": {
    eyebrow: "Dermatologia estética",
    title: "Naturalidade começa com um plano individualizado.",
    lead: "Procedimentos dermatológicos planejados a partir da anatomia, da saúde da pele e dos objetivos de cada paciente, em Copacabana, no Rio de Janeiro.",
    introTitle: "A melhor indicação depende do que realmente precisa ser tratado.",
    intro: [
      "Textura irregular, manchas, cicatrizes de acne, flacidez e sinais do envelhecimento exigem estratégias diferentes — e nem todo procedimento serve para todo caso. Na dermatologia estética, o ponto de partida não é a técnica, e sim o diagnóstico: entender o que de fato precisa ser tratado na pele de cada paciente para, então, escolher a abordagem mais adequada, com segurança e naturalidade.",
      "Vale procurar avaliação quando algum aspecto da pele incomoda de forma consistente, quando há dúvida sobre qual procedimento faz sentido ou quando tratamentos anteriores não trouxeram o resultado esperado. A avaliação médica também identifica condições de pele que precisam ser tratadas antes de qualquer procedimento estético.",
      "A consulta começa com o exame da pele e uma conversa sobre objetivos, histórico de saúde e expectativas. O dermatologista explica benefícios, limitações, riscos e tempo de recuperação de cada opção antes de qualquer decisão, e o plano pode ser dividido em etapas, com reavaliações para acompanhar a resposta da pele ao longo do tratamento.",
    ],
    topics: [
      ["Textura e sinais do envelhecimento", "Poros dilatados, linhas finas, perda de luminosidade e flacidez inicial podem ser abordados com procedimentos que estimulam a produção de colágeno, conforme avaliação. A escolha depende do tipo de pele, da queixa principal e do tempo de recuperação aceitável para cada paciente."],
      ["Manchas", "Melasma, manchas solares e outras hiperpigmentações têm origens e profundidades diferentes, o que muda a conduta. A avaliação do tipo de pigmentação precede a indicação de peelings, laser ou tratamentos tópicos, sempre associada a orientações de proteção solar."],
      ["Cicatrizes de acne", "As cicatrizes variam em tipo e profundidade, e é comum que um mesmo paciente apresente mais de um padrão. O tratamento costuma combinar técnicas em sessões planejadas, com expectativa realista de melhora gradual ao longo do tempo."],
      ["Toxina botulínica", "Utilizada no tratamento de rugas dinâmicas — as que aparecem com o movimento da face — e em outras indicações dermatológicas avaliadas em consulta. O planejamento considera a anatomia e a expressão de cada rosto, buscando um resultado equilibrado."],
      ["Preenchimentos", "Repõem volume ou oferecem suporte estrutural em áreas selecionadas, a partir de planejamento anatômico individualizado. A consulta discute indicações, limites e durabilidade esperada, priorizando segurança e harmonia com as características do paciente."],
      ["Procedimentos cirúrgicos", "Blefaroplastia (cirurgia das pálpebras), correção de cicatrizes e outros procedimentos selecionados podem ser indicados após avaliação criteriosa. O paciente recebe orientações detalhadas sobre preparo, recuperação e cuidados após a cirurgia."],
    ],
    process,
    doctor: "Dr. Miguel Ceccarelli",
    credential: "CRM-RJ 52-1092456 · RQE 34414",
    doctorText: "Dermatologista com atuação em dermatologia estética, o Dr. Miguel conduz cada indicação a partir de um planejamento individualizado, alinhado à anatomia e aos objetivos do paciente.",
    doctorImage: "/images/dr-miguel.webp",
    faq: [
      ["O resultado fica natural?", "O planejamento busca equilíbrio e respeito às características de cada rosto e de cada pele, evitando excessos. Ainda assim, os resultados variam de pessoa para pessoa, e as expectativas são alinhadas antes de qualquer procedimento."],
      ["Todo procedimento exige afastamento das atividades?", "Não. Alguns permitem retorno imediato à rotina, enquanto outros pedem alguns dias de recuperação. O tempo esperado para cada técnica é explicado na consulta, para que o paciente possa se programar."],
      ["É possível combinar tratamentos?", "Em alguns casos, sim. A combinação pode ser útil quando as queixas têm causas diferentes, mas a sequência e o intervalo entre as sessões devem ser definidos pelo médico, conforme a resposta da pele."],
      ["Preciso de avaliação antes de agendar um procedimento?", "Sim. A consulta de avaliação define se o procedimento é adequado ao seu caso, esclarece riscos e alternativas e permite planejar etapas e intervalos com segurança. É nela que o plano de tratamento é construído."],
      ["Quem tem melasma ou pele sensível pode fazer procedimentos?", "Muitas vezes sim, mas a escolha da técnica e dos parâmetros precisa considerar o risco de manchas e de irritação. Em alguns casos, a pele é preparada antes, e o tratamento avança de forma mais gradual, conforme avaliação."],
    ],
    related: [
      ["Cuidados com a pele", "/blog"],
      ["Biópsia de pele", "/blog/biopsia-de-pele-quando-e-indicada"],
    ],
  },
};
