import type { Metadata } from "next";
import { CtaBand, Footer, Header } from "../ui";

export const metadata: Metadata = { title: "Queda de Cabelo e Tricologia no Rio de Janeiro | QARA", description: "Avaliação da queda capilar, alopecias, couro cabeludo e transplante capilar com Dra. Diana Stohmann em Copacabana.",alternates:{canonical:"/cabelo"} };

const hairConditions = [["Alopecia androgenética","Afinamento progressivo e redução da densidade capilar em homens e mulheres."],["Eflúvio telógeno","Queda difusa que pode ocorrer após estresse, doenças, cirurgias, parto ou alterações nutricionais."],["Alopecia areata","Queda em áreas delimitadas associada a um processo autoimune."],["Alopecias cicatriciais","Inflamações que podem causar dano permanente ao folículo e exigem diagnóstico precoce."],["Doenças do couro cabeludo","Dermatite seborreica, psoríase, infecções, coceira e descamação persistente."],["Transplante capilar","Avaliação da área doadora, padrão de perda e possibilidade de restauração cirúrgica pela técnica FUE."]];

export default function HairPage(){return <><Header/><main id="conteudo">
  <section className="specialty-hero hair-hero"><div className="shell specialty-hero-grid"><div><p className="kicker">Cabelos e couro cabeludo</p><h1>Descubra a causa da queda antes de escolher o tratamento.</h1><p className="lead">Consulta com exame do couro cabeludo e tricoscopia — ampliação dos fios e folículos — para investigar alopecias, queda e sintomas locais.</p><div className="actions"><a className="button craft-primary" href="https://wa.me/5521992189718?text=Olá%2C%20gostaria%20de%20consultar%20horários%20com%20a%20Dra.%20Diana.">Consultar horários com a Dra. Diana</a><a className="quiet-link" href="#condicoes">Ver condições atendidas ↓</a></div></div><div className="specialty-portrait"><img src="/images/dra-diana.webp" alt="Dra. Diana Stohmann, dermatologista especialista em tricologia" width={1200} height={1423} fetchPriority="high" /></div></div></section>

  <section className="section shell intro-split"><div><p className="kicker">Avaliação capilar</p><h2>Queda de cabelo não é um diagnóstico único.</h2></div><div><p>A perda dos fios pode estar relacionada a fatores genéticos, hormonais, autoimunes, inflamatórios, nutricionais ou eventos recentes de saúde. Condições diferentes podem produzir sintomas semelhantes.</p><p>A consulta combina histórico clínico, exame do couro cabeludo e tricoscopia. Exames laboratoriais ou biópsia podem ser solicitados quando ajudam a esclarecer a causa.</p></div></section>

  <section className="specialty-soft" id="condicoes"><div className="shell section"><div className="editorial-heading"><div><p className="kicker">Áreas de atuação</p><h2>Condições avaliadas.</h2></div><p>O tratamento depende do diagnóstico e pode envolver medidas clínicas, medicamentos tópicos ou orais e procedimentos realizados no couro cabeludo.</p></div><div className="procedure-list">{hairConditions.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

  <section className="section shell treatment-feature"><div><p className="kicker">Diagnóstico e tratamento</p><h2>Recursos escolhidos conforme cada caso.</h2><p>Tricoscopia, biópsia do couro cabeludo, acompanhamento fotográfico, tratamentos tópicos e sistêmicos, intradermoterapia, microagulhamento e laser podem fazer parte do cuidado quando indicados.</p><p>O objetivo é tratar a causa, reduzir a progressão e acompanhar a resposta ao longo do tempo — sem protocolos iguais para todos.</p></div><div className="treatment-photo"><img src="/images/qara-atendimento.webp" alt="Avaliação dermatológica na Clínica QARA" width={1920} height={1280} loading="lazy" decoding="async" /></div></section>

  <section className="doctor-band hair-doctor-band"><div className="shell doctor-band-grid"><div className="doctor-band-photo"><img src="/images/dra-diana.webp" alt="Dra. Diana Stohmann" width={1200} height={1423} loading="lazy" decoding="async" /></div><div><p className="kicker light">Especialista responsável</p><h2>Dra. Diana Stohmann</h2><p className="credential-light">CRM-RJ 52.1305301 · RQE 57357</p><p>Dermatologista com pós-graduação em Dermatologia e fellow em Tricologia pelo Instituto Professor Rubem David Azulay. Atua em doenças dos cabelos e transplante capilar pela técnica FUE.</p><a href="https://wa.me/5521992189718?text=Olá%2C%20gostaria%20de%20agendar%20uma%20consulta%20com%20a%20Dra.%20Diana.">Agendar consulta →</a></div></div></section>

  <section className="section shell specialty-faq"><div><p className="kicker">Perguntas frequentes</p><h2>Dúvidas sobre queda capilar.</h2></div><div className="practical-list"><details><summary>Queda de cabelo em mulheres também pode ser genética?</summary><p>Sim. A alopecia androgenética também ocorre em mulheres e costuma produzir afinamento progressivo, frequentemente mais difuso.</p></details><details><summary>Quando a biópsia do couro cabeludo é indicada?</summary><p>Pode ser útil quando o exame e a tricoscopia não esclarecem o diagnóstico ou quando há suspeita de alopecia cicatricial e outras doenças inflamatórias.</p></details><details><summary>Todo paciente com calvície pode fazer transplante?</summary><p>Não. É necessário avaliar diagnóstico, estabilidade da queda, qualidade da área doadora, expectativas e condições clínicas.</p></details><details><summary>A consulta pode ser feita por telemedicina?</summary><p>Algumas orientações e acompanhamentos podem ser realizados online, mas a tricoscopia, a biópsia e o planejamento de procedimentos exigem avaliação presencial.</p></details></div></section>
  <CtaBand/>
  </main><Footer/></>}
