import type { Metadata } from "next";
import { Breadcrumb, CtaBand, Footer, Header } from "../ui";

export const metadata: Metadata = { title: "Queda de Cabelo e Tricologia no Rio de Janeiro | QARA", description: "Queda de cabelo, alopecias e doenças do couro cabeludo: consulta com tricoscopia e avaliação de transplante capilar FUE em Copacabana, Rio de Janeiro.",alternates:{canonical:"/cabelo"} };

const hairConditions = [["Alopecia androgenética","Afinamento progressivo dos fios e redução da densidade capilar, de origem genética e hormonal, que pode afetar homens e mulheres em padrões diferentes. A investigação costuma incluir a tricoscopia, e o tratamento busca desacelerar a progressão e preservar os fios existentes, conforme avaliação individual."],["Eflúvio telógeno","Queda difusa e geralmente temporária que pode surgir semanas ou meses após estresse intenso, doenças, cirurgias, parto ou alterações nutricionais. A avaliação procura identificar o gatilho e afastar outras causas de queda; exames laboratoriais podem ser solicitados quando ajudam a esclarecer o quadro."],["Alopecia areata","Queda em áreas delimitadas, muitas vezes arredondadas, associada a um processo autoimune em que a inflamação atinge o folículo sem destruí-lo. O diagnóstico costuma ser clínico e tricoscópico, e o tratamento é ajustado conforme a extensão das áreas e a atividade da doença."],["Alopecias cicatriciais","Grupo de doenças inflamatórias em que o folículo pode ser substituído por tecido cicatricial, com risco de perda definitiva dos fios na área afetada. Por isso, o diagnóstico precoce — muitas vezes com apoio da biópsia do couro cabeludo — é importante para orientar o controle da inflamação."],["Doenças do couro cabeludo","Dermatite seborreica, psoríase, infecções e quadros de coceira ou descamação persistente que incomodam no dia a dia e podem interferir na saúde dos fios. O exame do couro cabeludo e a tricoscopia ajudam a diferenciar essas condições, e o tratamento é direcionado à causa identificada."],["Transplante capilar","Restauração cirúrgica indicada em casos selecionados, após avaliação do diagnóstico, do padrão de perda e da qualidade da área doadora. Na técnica FUE (extração de unidades foliculares), os folículos são retirados individualmente e implantados nas áreas de rarefação, conforme planejamento individual."]];

const faqs: [string, string][] = [
  ["Queda de cabelo em mulheres também pode ser genética?", "Sim. A alopecia androgenética também ocorre em mulheres e costuma produzir afinamento progressivo, frequentemente mais difuso do que no padrão masculino. A avaliação também investiga fatores hormonais e outras causas que podem se somar ao quadro."],
  ["Quando a biópsia do couro cabeludo é indicada?", "A biópsia — retirada de um pequeno fragmento do couro cabeludo para análise — pode ser útil quando o exame clínico e a tricoscopia não esclarecem o diagnóstico, ou quando há suspeita de alopecia cicatricial e outras doenças inflamatórias."],
  ["Todo paciente com calvície pode fazer transplante?", "Não. Antes de indicar o transplante, é necessário avaliar o diagnóstico, a estabilidade da queda, a qualidade da área doadora, as expectativas e as condições clínicas. Em alguns casos, o tratamento clínico vem antes ou acompanha a cirurgia."],
  ["Quanto tempo leva para ver resultado do tratamento da queda de cabelo?", "Varia conforme o diagnóstico e o tratamento escolhido. O ciclo de crescimento dos fios é naturalmente lento, e a resposta costuma ser avaliada ao longo de meses, em consultas de acompanhamento — muitas vezes com apoio de fotografias e tricoscopia comparativa."],
  ["Preciso fazer exames de sangue para investigar a queda de cabelo?", "Nem sempre. Exames laboratoriais podem ser solicitados quando a história clínica ou o exame sugerem fatores hormonais, nutricionais ou doenças associadas contribuindo para a queda. A necessidade é definida na consulta, conforme avaliação individual."],
  ["A consulta pode ser feita por telemedicina?", "Algumas orientações e acompanhamentos podem ser realizados online, mas a tricoscopia, a biópsia e o planejamento de procedimentos exigem avaliação presencial."],
];

const schema={"@context":"https://schema.org","@type":"MedicalWebPage",name:"Cabelos e couro cabeludo",description:"Avaliação da queda capilar, alopecias, couro cabeludo e transplante capilar em Copacabana.",inLanguage:"pt-BR",url:"https://clinicaqara.com.br/cabelo",mainEntityOfPage:"https://clinicaqara.com.br/cabelo",about:{"@type":"MedicalSpecialty",name:"Tricologia"},author:{"@type":"Physician",name:"Dra. Diana Stohmann",medicalSpecialty:"Dermatology",identifier:["CRM-RJ 52.1305301","RQE 57357"],worksFor:{"@type":"MedicalClinic",name:"Clínica QARA",url:"https://clinicaqara.com.br"}}};

const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};

export default function HairPage(){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><Header/><main id="conteudo">
  <section className="specialty-hero hair-hero"><Breadcrumb>Cabelos e couro cabeludo</Breadcrumb><div className="shell specialty-hero-grid"><div><p className="kicker">Cabelos e couro cabeludo</p><h1>Descubra a causa da queda antes de escolher o tratamento.</h1><p className="lead">Consulta com exame do couro cabeludo e tricoscopia — ampliação dos fios e folículos — para investigar alopecias, queda e sintomas locais.</p><div className="actions"><a className="button craft-primary" href="https://wa.me/5521992189718?text=Olá%2C%20gostaria%20de%20consultar%20horários%20com%20a%20Dra.%20Diana.">Consultar horários com a Dra. Diana</a><a className="quiet-link" href="#condicoes">Ver condições atendidas ↓</a></div></div><div className="specialty-portrait"><img src="/images/dra-diana.webp" srcSet="/images/dra-diana-640.webp 640w, /images/dra-diana-1024.webp 1024w, /images/dra-diana.webp 1200w" sizes="(max-width: 900px) 100vw, 45vw" alt="Dra. Diana Stohmann, dermatologista especialista em tricologia" width={1200} height={1423} fetchPriority="high" /></div></div></section>

  <section className="section shell intro-split"><div><p className="kicker">Avaliação capilar</p><h2>Queda de cabelo não é um diagnóstico único.</h2></div><div><p>A perda dos fios pode estar relacionada a fatores genéticos, hormonais, autoimunes, inflamatórios, nutricionais ou a eventos recentes de saúde. Condições diferentes podem produzir sintomas muito semelhantes — e mais de uma causa pode coexistir na mesma pessoa.</p><p>Por isso, tratar a queda sem investigar a origem pode adiar o cuidado adequado. Identificar o tipo de alopecia é o que orienta a escolha do tratamento e ajuda a construir expectativas realistas sobre a resposta.</p><p>A consulta combina histórico clínico detalhado, exame do couro cabeludo e tricoscopia — a observação dos fios e folículos com ampliação. Exames laboratoriais ou biópsia podem ser solicitados quando ajudam a esclarecer a causa.</p></div></section>

  <section className="specialty-soft" id="condicoes"><div className="shell section"><div className="editorial-heading"><div><p className="kicker">Áreas de atuação</p><h2>Condições avaliadas.</h2></div><p>O tratamento depende do diagnóstico e pode envolver medidas clínicas, medicamentos tópicos ou orais e procedimentos realizados no couro cabeludo.</p></div><div className="procedure-list">{hairConditions.map(([title,text])=><article key={title}><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

  <section className="section shell treatment-feature"><div><p className="kicker">Diagnóstico e tratamento</p><h2>Recursos escolhidos conforme cada caso.</h2><p>A tricoscopia permite observar, com ampliação, sinais que não aparecem a olho nu: variações na espessura dos fios, sinais de inflamação e padrões que ajudam a diferenciar os tipos de alopecia. Também serve para acompanhar a evolução ao longo do tratamento, de forma objetiva.</p><p>Conforme o diagnóstico, o cuidado pode incluir tratamentos tópicos e sistêmicos, intradermoterapia — a aplicação de medicamentos diretamente no couro cabeludo —, microagulhamento, laser, biópsia quando necessária e acompanhamento fotográfico.</p><p>O objetivo é tratar a causa, reduzir a progressão e avaliar a resposta ao longo do tempo — sem protocolos iguais para todos, porque cada quadro pede uma estratégia própria.</p></div><div className="treatment-photo"><img src="/images/qara-atendimento.webp" srcSet="/images/qara-atendimento-640.webp 640w, /images/qara-atendimento-1024.webp 1024w, /images/qara-atendimento.webp 1920w" sizes="(max-width: 900px) 100vw, 50vw" alt="Avaliação dermatológica na Clínica QARA" width={1920} height={1280} loading="lazy" decoding="async" /></div></section>

  <section className="doctor-band hair-doctor-band"><div className="shell doctor-band-grid"><div className="doctor-band-photo"><img src="/images/dra-diana.webp" srcSet="/images/dra-diana-640.webp 640w, /images/dra-diana-1024.webp 1024w, /images/dra-diana.webp 1200w" sizes="(max-width: 900px) 100vw, 40vw" alt="Dra. Diana Stohmann" width={1200} height={1423} loading="lazy" decoding="async" /></div><div><p className="kicker light">Especialista responsável</p><h2>Dra. Diana Stohmann</h2><p className="credential-light">CRM-RJ 52.1305301 · RQE 57357</p><p>Dermatologista com pós-graduação em Dermatologia e fellow em Tricologia pelo Instituto Professor Rubem David Azulay. Atua em doenças dos cabelos e transplante capilar pela técnica FUE.</p><a href="https://wa.me/5521992189718?text=Olá%2C%20gostaria%20de%20agendar%20uma%20consulta%20com%20a%20Dra.%20Diana.">Agendar consulta →</a></div></div></section>

  <section className="section shell specialty-faq"><div><p className="kicker">Perguntas frequentes</p><h2>Dúvidas sobre queda capilar.</h2></div><div className="practical-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <CtaBand/>
  </main><Footer/></>}
